"""openshell_launch.py -- run a hooked agent session inside an OpenShell sandbox (OASP R1).

Optional. The monitor works without OpenShell. Where OpenShell is installed
(Linux or macOS natively; on this Windows machine only inside WSL, where
OpenShell marks support experimental), the sandbox adds what the hook cannot:
a kernel filesystem boundary (Landlock), a network fence that admits only the
policy's endpoints with `enforcement: enforce`, and provider credentials that
never enter the sandbox. The hook still makes every hold decision; OpenShell
is the backstop when a rule misses, and its gateway log feeds ocsf_import.py.

This module builds the policy from the owner's config and the commands to run.
It runs nothing unless asked (`run=True`). Steps:

1. `openshell sandbox create --detach` with the generated policy, the
   provider profile and the workspace upload (OpenShell cannot combine
   `--upload` with a trailing command, so the agent starts in step 2);
2. `openshell sandbox exec --tty` starts the agent inside;
3. from the host, `openshell sandbox download` copies the monitor store and
   the harness transcripts out, and `flywheel monitor witness` checks them
   with the witness directory kept on the host, outside the sandbox.

The hook settings must reach the sandbox read-only: bake a managed settings
file into the image under /etc (read-only in every OpenShell policy here), so
the agent cannot edit its own hook block. See docs/PREACTION-OPENSHELL.md.
Unverified here: no OpenShell binary was installed on the build machine, so
the commands were checked against OpenShell's docs at commit 82e8893 and
against a fake binary in the tests, not against a running gateway.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

SANDBOX_WORKDIR = "/sandbox/work"
SANDBOX_HOME = "/sandbox/.flywheel-preaction"
AGENT_BINARIES = ("/usr/bin/claude", "/usr/local/bin/claude", "/usr/bin/codex",
                  "/usr/local/bin/codex", "/usr/bin/curl", "/usr/bin/node", "/usr/local/bin/node")
_CLIENT_CMD = {"claude-code": "claude", "codex": "codex"}


def detect(which=shutil.which, platform: str = sys.platform, runner=subprocess.run) -> dict:
    """Where OpenShell can run from here: native, through WSL, or not at all."""
    if platform != "win32":
        path = which("openshell")
        return ({"available": True, "route": "native", "prefix": [path]} if path else
                {"available": False, "route": "none", "prefix": [],
                 "reason": "openshell is not on PATH"})
    if not which("wsl.exe") and not which("wsl"):
        return {"available": False, "route": "none", "prefix": [], "windows": True,
                "reason": "native Windows needs OpenShell's MXC driver (RFC 0013, in review); "
                          "WSL is not installed"}
    try:
        proc = runner(["wsl.exe", "-e", "sh", "-lc", "command -v openshell"],
                      capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError) as exc:
        return {"available": False, "route": "none", "prefix": [], "windows": True,
                "reason": f"wsl probe failed: {type(exc).__name__}"}
    if proc.returncode == 0 and proc.stdout.strip():
        return {"available": True, "route": "wsl",
                "prefix": ["wsl.exe", "-e", proc.stdout.strip().splitlines()[-1]]}
    return {"available": False, "route": "none", "prefix": [], "windows": True,
            "reason": "openshell is not installed inside WSL"}


def _endpoint(host: str, access: str) -> list:
    return [f"      - host: {host}", "        port: 443", "        protocol: rest",
            "        enforcement: enforce", f"        access: {access}"]


def policy_yaml(owner, binaries=AGENT_BINARIES) -> str:
    """An OpenShell v1 policy from the owner's hosts. Every endpoint is
    `enforcement: enforce` (OpenShell's default is audit, which allows).
    Fetch hosts are read-only; allow hosts are read-write. /etc stays
    read-only so a managed hook settings file there cannot be edited."""
    lines = ["# Generated by flywheel monitor sandbox from the owner config.",
             "# Model API endpoints come from the provider profile, not from here.",
             "version: 1", "filesystem_policy:", "  include_workdir: true",
             "  read_only: [/usr, /lib, /etc, /proc, /dev/urandom]",
             "  read_write: [/tmp, /dev/null]", "network_policies:"]
    groups = (("owner_fetch_hosts", owner.fetch_hosts, "read-only"),
              ("owner_allow_hosts", owner.allow_hosts, "read-write"))
    wrote = False
    for name, hosts, access in groups:
        if not hosts:
            continue
        wrote = True
        lines += [f"  {name}:", "    endpoints:"]
        for h in hosts:
            lines += _endpoint(h, access)
        lines += ["    binaries:"] + [f"      - path: {b}" for b in binaries]
    if not wrote:
        lines[-1] = "network_policies: {}"
    return "\n".join(lines) + "\n"


def wsl_path(path: str) -> str:
    """A Windows drive path (C:/dev/x) as /mnt/c/dev/x, for a WSL-side openshell."""
    p = str(path).replace("\\", "/")
    if len(p) > 1 and p[1] == ":":
        return f"/mnt/{p[0].lower()}{p[2:]}"
    return p


def commands(client: str, *, name: str, policy_path: str, workspace: str,
             provider: str = "", image: str = "", prefix=("openshell",)) -> dict:
    if client not in _CLIENT_CMD:
        raise ValueError("client must be claude-code or codex")
    pre = list(prefix)
    create = pre + ["sandbox", "create", "--name", name, "--detach", "--policy", policy_path,
                    "--upload", f"{workspace}:{SANDBOX_WORKDIR}"]
    if provider:
        create += ["--provider", provider]
    if image:
        create += ["--from", image]
    start = pre + ["sandbox", "exec", "-n", name, "--tty", "--", _CLIENT_CMD[client]]
    pull = pre + ["sandbox", "download", name, SANDBOX_HOME, "<host-dir>/store"]
    return {"create": create, "start": start, "pull_store": pull}


def plan(client: str, *, owner, workspace: str, out_dir, name: str = "flywheel-hooked",
         provider: str = "", image: str = "", detected: dict | None = None) -> dict:
    """Write the policy file and return the commands, without running them."""
    det = detected if detected is not None else detect()
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    policy = out / f"{name}.policy.yaml"
    policy.write_text(policy_yaml(owner), encoding="utf-8")
    # On Windows the only route today is WSL, so even an unavailable plan is
    # printed in the form a WSL-side openshell would take.
    via_wsl = det["route"] == "wsl" or (det["route"] == "none" and det.get("windows"))
    conv = wsl_path if via_wsl else str
    prefix = det.get("prefix") or (["wsl.exe", "-e", "openshell"] if via_wsl else ["openshell"])
    cmds = commands(client, name=name, policy_path=conv(str(policy)), workspace=conv(workspace),
                    provider=provider or ("claude-code" if client == "claude-code" else ""),
                    image=image, prefix=prefix)
    return {"available": det["available"], "route": det["route"],
            "reason": det.get("reason", ""), "policy_path": str(policy), "commands": cmds,
            "telemetry_note": "Set OPENSHELL_TELEMETRY_ENABLED=false on the gateway, and drop "
                              "statsig.anthropic.com and sentry.io from the Claude Code "
                              "provider profile if your policy forbids that traffic."}


def run(plan_: dict, runner=subprocess.run) -> int:
    """Create the sandbox, then start the agent. Refuses when OpenShell is absent."""
    if not plan_["available"]:
        return 3
    for step in ("create", "start"):
        proc = runner(plan_["commands"][step])
        if proc.returncode != 0:
            return int(proc.returncode) or 1
    return 0


def to_json(plan_: dict) -> str:
    return json.dumps(plan_, indent=2)
