"""build_access_gap_snapshot.py -- regenerate harness/trace_observation/access_gap_data.py.

Usage: python scripts/build_access_gap_snapshot.py PATH/TO/access-gap.json

Reads a provider-access-gap-record (schema 0.1.x) and writes the public API
surface for the six core providers, plus every source those cells cite, into a
Python module so the snapshot ships with the package. Consumer, enterprise and
pre-deployment rows stay out: they bear on what an evaluator could request,
not on what a capture adapter can read on a call. The source file's sha256 is
recorded so a reader can tie the snapshot to the record it came from.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

CORE = ("openai", "anthropic", "google", "xai", "deepseek", "mistral")
OUT = Path("harness") / "trace_observation" / "access_gap_data.py"
HEADER = '''"""access_gap_data.py -- generated by scripts/build_access_gap_snapshot.py. Do not edit.

API-surface cells of the provider access-gap record for six core providers, and
the sources they cite. Each cell is a documentation claim read on its source's
read date; it becomes an observation only when a live call agrees with it.
"""
'''


def build(src: Path) -> str:
    raw = src.read_bytes()
    rec = json.loads(raw)
    cells = [c for c in rec["cells"] if c["surface"] == "api" and c["provider"] in CORE]
    cited = {s for c in cells for s in c["source_ids"]}
    sources = [s for s in rec["sources"] if s["id"] in cited]
    lines = [HEADER, "", f"SCHEMA = {rec['schema']!r}", f"SCHEMA_VERSION = {rec['schema_version']!r}",
             f"COMPILED = {rec['compiled']!r}",
             f"SOURCE_SHA256 = {hashlib.sha256(raw).hexdigest()!r}",
             f"FIELDS = {sorted({c['field'] for c in cells})!r}", "", "CELLS = ["]
    for c in cells:
        lines.append("    " + repr({k: c[k] for k in ("provider", "field", "value", "confidence",
                                                     "source_ids", "detail")}) + ",")
    lines += ["]", "", "SOURCES = ["]
    for s in sources:
        lines.append("    " + repr({k: s.get(k) for k in ("id", "publisher", "kind", "url",
                                                         "read_date", "page_date", "read_method",
                                                         "confidence")}) + ",")
    lines += ["]", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 1:
        print(__doc__)
        return 2
    OUT.write_text(build(Path(argv[0])), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
