#!/usr/bin/env python3
"""seed_hard_v2_b8.py - batch 8 for the N>=100 hard-set lane (target ~80/100).

Same contract as batches 1-7: soundness admission through task_curator gates;
difficulty screening against the served 14B is a later arm. Batch 8 doctrine:
contract density over textbook fame, extended to stateful and search-shaped
contracts. Difficulty comes from precise multi-clause prose contracts
(validation ordering, exact exception types and messages, tie-breaking,
budget semantics, trace shapes) not famous algorithms. Domains in this file
are ones batches 1-7 barely touch: combinatorial ranking and unranking
(permutation rank, Gray-code rank, kth combination), bounded sequence
processes (look-and-say with run overflow, longest digit run, Collatz under a
step budget), BFS and graph contracts (knight moves, grid shortest path,
union-find components, strict bipartite check, one-way portal board,
multi-source spread radius), stateful trace simulations (LRU cache,
min-stack, ring buffer), fold and ledger contracts (k-smallest ranking, bank
ledger with formatted errors, inventory reservation), and strict parsing or
encoding (URL splitting, quoted-printable decoding, INI sections, minimal LCS
diff, Fletcher-16 checksum, markdown outline numbering). Each task is a
single top-level function; the prompt states the full contract in prose with
no solution code; the hidden tests assert exact semantics on adversarial
edges.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from harness.task_curator import seed_batch
from harness.tasks_lib import TaskSpec

REGISTRY_PATH = Path(__file__).parent.parent / "tasks" / "curated" / "hard_v2.jsonl"

BATCH = [
    TaskSpec(
        'perm_rank',
        "Write a Python function perm_rank(perm) that returns the 0-based rank of a permutation in the lexicographic ordering of all permutations of 0..n-1. perm must be a list; otherwise -> ValueError('bad input'). Every element must be an int and not a bool; any other element -> ValueError('bad element'). The list must contain every integer from 0 to len(perm)-1 exactly once; a duplicate, a missing value, or an out-of-range value -> ValueError('not a permutation'). Checks run in that order: the list check, then the element type check across all elements, then the permutation check. Among the n! permutations of 0..n-1 listed in ascending lexicographic order, return the position of perm counting from 0, so [0, 1, ..., n-1] has rank 0 and the fully descending permutation has rank n! - 1. The empty list is the unique permutation of nothing and has rank 0. Output ONLY the function definition.",
        'solution.py',
        'def perm_rank(perm):\n    if not isinstance(perm, list):\n        raise ValueError("bad input")\n    for x in perm:\n        if not isinstance(x, int) or isinstance(x, bool):\n            raise ValueError("bad element")\n    n = len(perm)\n    if sorted(perm) != list(range(n)):\n        raise ValueError("not a permutation")\n    rank = 0\n    for i in range(n):\n        smaller = sum(1 for y in perm[i + 1:] if y < perm[i])\n        f = 1\n        for m in range(2, n - i):\n            f *= m\n        rank += smaller * f\n    return rank\n',
        "import pytest\nfrom solution import perm_rank as f\ndef test_empty(): assert f([]) == 0\ndef test_single(): assert f([0]) == 0\ndef test_identity(): assert f([0, 1, 2]) == 0\ndef test_reversed(): assert f([2, 1, 0]) == 5\ndef test_middle(): assert f([1, 0, 2]) == 2\ndef test_middle2(): assert f([1, 2, 0]) == 3\ndef test_larger(): assert f([3, 1, 4, 2, 0]) == 83\ndef test_missing():\n    with pytest.raises(ValueError) as e: f([0, 2])\n    assert str(e.value) == 'not a permutation'\ndef test_duplicate():\n    with pytest.raises(ValueError) as e: f([0, 0])\n    assert str(e.value) == 'not a permutation'\ndef test_bad_element():\n    with pytest.raises(ValueError) as e: f([0.5])\n    assert str(e.value) == 'bad element'\ndef test_bool_element():\n    with pytest.raises(ValueError) as e: f([True, 0])\n    assert str(e.value) == 'bad element'\ndef test_bad_input():\n    with pytest.raises(ValueError) as e: f('012')\n    assert str(e.value) == 'bad input'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'gray_rank',
        "Write a Python function gray_rank(bits) that returns the 0-based position of a codeword in the reflected binary Gray code sequence, as an int. bits must be a str; otherwise -> ValueError('bad code'). It must be non-empty and every character must be the digit 0 or the digit 1; otherwise -> ValueError('bad code'). The width n is the length of bits, and the n-bit sequence lists, for each index i from 0 to 2**n - 1, the value i xor (i right-shifted by one bit), printed as exactly n binary digits with the most significant bit first. gray_rank inverts that listing: given the printed codeword it returns the index i at which the codeword appears. So in the 3-bit sequence '000' is at index 0, '001' at 1, '011' at 2, '010' at 3, '110' at 4, '111' at 5, '101' at 6, and '100' at 7. Leading zeros only widen the printing and never change the index, so '0011' in the 4-bit sequence is also at index 2. Output ONLY the function definition.",
        'solution.py',
        'def gray_rank(bits):\n    if not isinstance(bits, str) or bits == "":\n        raise ValueError("bad code")\n    for c in bits:\n        if c not in "01":\n            raise ValueError("bad code")\n    g = int(bits, 2)\n    i = 0\n    while g:\n        i ^= g\n        g >>= 1\n    return i\n',
        "import pytest\nfrom solution import gray_rank as f\ndef test_zero(): assert f('0') == 0\ndef test_one(): assert f('1') == 1\ndef test_three_bit_2(): assert f('011') == 2\ndef test_three_bit_3(): assert f('010') == 3\ndef test_three_bit_4(): assert f('110') == 4\ndef test_three_bit_6(): assert f('101') == 6\ndef test_three_bit_7(): assert f('100') == 7\ndef test_leading_zeros(): assert f('0011') == 2\ndef test_roundtrip():\n    for i in range(64):\n        assert f(format(i ^ (i >> 1), '06b')) == i\ndef test_empty():\n    with pytest.raises(ValueError) as e: f('')\n    assert str(e.value) == 'bad code'\ndef test_bad_char():\n    with pytest.raises(ValueError) as e: f('012')\n    assert str(e.value) == 'bad code'\ndef test_not_string():\n    with pytest.raises(ValueError) as e: f(5)\n    assert str(e.value) == 'bad code'\n",
        'hard', max_new_tokens=512),
    TaskSpec(
        'kth_combination',
        "Write a Python function kth_combination(n, k, r) that returns the combination at rank r in the lexicographic listing of all k-element combinations of the integers 0..n-1, as a sorted list. n must be an int, not a bool, and at least 0; otherwise -> ValueError('bad n'). k must be an int, not a bool, and satisfy 0 <= k <= n; otherwise -> ValueError('bad k'). r must be an int, not a bool, and satisfy 0 <= r < C(n, k) where C is the binomial coefficient; otherwise -> ValueError('bad rank'). Checks run in that order: n first, then k, then r. Each combination is written as its ascending sorted list of members, and the combinations are listed in ascending lexicographic order of those lists, so for n = 4 and k = 2 the listing is [0,1], [0,2], [0,3], [1,2], [1,3], [2,3] and rank 3 is [1,2]. When k is 0 the only combination is the empty list at rank 0, so any other rank -> ValueError('bad rank'). Output ONLY the function definition.",
        'solution.py',
        'def kth_combination(n, k, r):\n    if not isinstance(n, int) or isinstance(n, bool) or n < 0:\n        raise ValueError("bad n")\n    if not isinstance(k, int) or isinstance(k, bool) or k < 0 or k > n:\n        raise ValueError("bad k")\n\n    def comb(a, b):\n        if b < 0 or b > a:\n            return 0\n        b = min(b, a - b)\n        num = 1\n        for j in range(b):\n            num = num * (a - j) // (j + 1)\n        return num\n\n    total = comb(n, k)\n    if not isinstance(r, int) or isinstance(r, bool) or r < 0 or r >= total:\n        raise ValueError("bad rank")\n    out = []\n    x = 0\n    remaining = k\n    rr = r\n    while remaining > 0:\n        c = comb(n - x - 1, remaining - 1)\n        if rr < c:\n            out.append(x)\n            remaining -= 1\n        else:\n            rr -= c\n        x += 1\n    return out\n',
        "import pytest\nfrom solution import kth_combination as f\ndef test_first(): assert f(4, 2, 0) == [0, 1]\ndef test_middle(): assert f(4, 2, 3) == [1, 2]\ndef test_last(): assert f(4, 2, 5) == [2, 3]\ndef test_five_three(): assert f(5, 3, 6) == [1, 2, 3]\ndef test_five_three_last(): assert f(5, 3, 9) == [2, 3, 4]\ndef test_k_zero(): assert f(3, 0, 0) == []\ndef test_k_equals_n(): assert f(3, 3, 0) == [0, 1, 2]\ndef test_n_zero(): assert f(0, 0, 0) == []\ndef test_bad_n():\n    with pytest.raises(ValueError) as e: f(-1, 0, 0)\n    assert str(e.value) == 'bad n'\ndef test_bool_n():\n    with pytest.raises(ValueError) as e: f(True, 1, 0)\n    assert str(e.value) == 'bad n'\ndef test_bad_k():\n    with pytest.raises(ValueError) as e: f(3, 4, 0)\n    assert str(e.value) == 'bad k'\ndef test_bool_k():\n    with pytest.raises(ValueError) as e: f(2, True, 0)\n    assert str(e.value) == 'bad k'\ndef test_bad_rank_high():\n    with pytest.raises(ValueError) as e: f(4, 2, 6)\n    assert str(e.value) == 'bad rank'\ndef test_bad_rank_neg():\n    with pytest.raises(ValueError) as e: f(4, 2, -1)\n    assert str(e.value) == 'bad rank'\ndef test_k_zero_rank_one():\n    with pytest.raises(ValueError) as e: f(3, 0, 1)\n    assert str(e.value) == 'bad rank'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'look_and_say_bounded',
        "Write a Python function look_and_say(seed, steps) that applies the look-and-say expansion a fixed number of times and returns the resulting string. seed must be a str, non-empty, and every character must be an ASCII decimal digit; otherwise -> ValueError('bad seed'). steps must be an int, not a bool, and at least 0; otherwise -> ValueError('bad steps'). Seed validation happens before steps validation. One step reads the current string left to right as maximal runs of equal digits and writes, for each run, the run length followed by the digit, so '3993' becomes '132913' and '1' becomes '11'. Reading is strict: if any run in the string being read is longer than 9 characters its length would not be a single digit, so raise ValueError('run overflow'). That check applies only when a step actually reads the string: with steps equal to 0 the seed is returned unchanged even if it contains a run longer than 9. Output ONLY the function definition.",
        'solution.py',
        'def look_and_say(seed, steps):\n    if not isinstance(seed, str) or seed == "":\n        raise ValueError("bad seed")\n    for c in seed:\n        if not ("0" <= c <= "9"):\n            raise ValueError("bad seed")\n    if not isinstance(steps, int) or isinstance(steps, bool) or steps < 0:\n        raise ValueError("bad steps")\n    cur = seed\n    for _ in range(steps):\n        out = []\n        i = 0\n        while i < len(cur):\n            j = i\n            while j < len(cur) and cur[j] == cur[i]:\n                j += 1\n            if j - i > 9:\n                raise ValueError("run overflow")\n            out.append(str(j - i))\n            out.append(cur[i])\n            i = j\n        cur = "".join(out)\n    return cur\n',
        "import pytest\nfrom solution import look_and_say as f\ndef test_zero_steps(): assert f('1', 0) == '1'\ndef test_one_step(): assert f('1', 1) == '11'\ndef test_four_steps(): assert f('1', 4) == '111221'\ndef test_five_steps(): assert f('1', 5) == '312211'\ndef test_runs(): assert f('3993', 1) == '132913'\ndef test_zero_digit(): assert f('0', 1) == '10'\ndef test_fixed_point(): assert f('22', 3) == '22'\ndef test_overflow():\n    with pytest.raises(ValueError) as e: f('1111111111', 1)\n    assert str(e.value) == 'run overflow'\ndef test_overflow_skipped_at_zero_steps():\n    assert f('1111111111', 0) == '1111111111'\ndef test_bad_seed_empty():\n    with pytest.raises(ValueError) as e: f('', 1)\n    assert str(e.value) == 'bad seed'\ndef test_bad_seed_char():\n    with pytest.raises(ValueError) as e: f('12a', 1)\n    assert str(e.value) == 'bad seed'\ndef test_bad_seed_type():\n    with pytest.raises(ValueError) as e: f(11, 1)\n    assert str(e.value) == 'bad seed'\ndef test_seed_before_steps():\n    with pytest.raises(ValueError) as e: f('', -1)\n    assert str(e.value) == 'bad seed'\ndef test_bad_steps_negative():\n    with pytest.raises(ValueError) as e: f('1', -1)\n    assert str(e.value) == 'bad steps'\ndef test_bad_steps_bool():\n    with pytest.raises(ValueError) as e: f('1', True)\n    assert str(e.value) == 'bad steps'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'longest_digit_run',
        "Write a Python function longest_digit_run(n) that locates the longest run of equal consecutive digits in the decimal representation of a non-negative integer. n must be an int, not a bool, and at least 0; otherwise -> ValueError('bad number'). Use the ordinary base-10 representation with no sign and no leading zeros; 0 is the single digit 0. A run is a maximal block of equal consecutive digits, meaning it cannot be extended on either side. Return a tuple of exactly three ints (start, length, digit): the 0-based index of the run's first digit counted from the most significant digit, the run's length, and the digit's numeric value. When several runs share the maximal length, return the leftmost one (the smallest start). A single-digit number returns (0, 1, that digit). Output ONLY the function definition.",
        'solution.py',
        'def longest_digit_run(n):\n    if not isinstance(n, int) or isinstance(n, bool) or n < 0:\n        raise ValueError("bad number")\n    s = str(n)\n    best_start, best_len = 0, 1\n    i = 0\n    while i < len(s):\n        j = i\n        while j < len(s) and s[j] == s[i]:\n            j += 1\n        if j - i > best_len:\n            best_start, best_len = i, j - i\n        i = j\n    return (best_start, best_len, int(s[best_start]))\n',
        "import pytest\nfrom solution import longest_digit_run as f\ndef test_zero(): assert f(0) == (0, 1, 0)\ndef test_single(): assert f(7) == (0, 1, 7)\ndef test_basic(): assert f(11222) == (2, 3, 2)\ndef test_front(): assert f(22211) == (0, 3, 2)\ndef test_tie_leftmost(): assert f(1122) == (0, 2, 1)\ndef test_zeros(): assert f(1000) == (1, 3, 0)\ndef test_alternating(): assert f(121212) == (0, 1, 1)\ndef test_three_way_tie(): assert f(9998887776) == (0, 3, 9)\ndef test_late_win(): assert f(12333) == (2, 3, 3)\ndef test_is_tuple(): assert type(f(11)) is tuple\ndef test_negative():\n    with pytest.raises(ValueError) as e: f(-5)\n    assert str(e.value) == 'bad number'\ndef test_bool():\n    with pytest.raises(ValueError) as e: f(True)\n    assert str(e.value) == 'bad number'\ndef test_string():\n    with pytest.raises(ValueError) as e: f('11')\n    assert str(e.value) == 'bad number'\n",
        'hard', max_new_tokens=512),
    TaskSpec(
        'collatz_trace',
        "Write a Python function collatz_trace(n, limit) that returns the full Collatz trajectory of n as a list, computed under a strict step budget. n must be an int, not a bool, and at least 1; otherwise -> ValueError('bad start'). limit must be an int, not a bool, and at least 0; otherwise -> ValueError('bad limit'). n is validated before limit. One step maps an even value to value // 2 and an odd value to 3 * value + 1. The trace starts with n itself and appends the value after each step, stopping once the value 1 has been appended; if n is already 1 the trace is [1] with zero steps taken, whatever the limit. Steps are transitions, so the trace always has exactly one more element than the number of steps taken. If reaching 1 would require MORE than limit steps, raise RuntimeError('limit exceeded') instead of returning; reaching 1 in exactly limit steps succeeds. The two failure kinds are distinct: validation failures are ValueError and budget exhaustion is RuntimeError. Output ONLY the function definition.",
        'solution.py',
        'def collatz_trace(n, limit):\n    if not isinstance(n, int) or isinstance(n, bool) or n < 1:\n        raise ValueError("bad start")\n    if not isinstance(limit, int) or isinstance(limit, bool) or limit < 0:\n        raise ValueError("bad limit")\n    trace = [n]\n    cur = n\n    steps = 0\n    while cur != 1:\n        if steps == limit:\n            raise RuntimeError("limit exceeded")\n        cur = cur // 2 if cur % 2 == 0 else 3 * cur + 1\n        trace.append(cur)\n        steps += 1\n    return trace\n',
        "import pytest\nfrom solution import collatz_trace as f\ndef test_one(): assert f(1, 0) == [1]\ndef test_two(): assert f(2, 1) == [2, 1]\ndef test_six(): assert f(6, 100) == [6, 3, 10, 5, 16, 8, 4, 2, 1]\ndef test_exact_budget(): assert f(6, 8) == [6, 3, 10, 5, 16, 8, 4, 2, 1]\ndef test_budget_short():\n    with pytest.raises(RuntimeError) as e: f(6, 7)\n    assert str(e.value) == 'limit exceeded'\ndef test_zero_budget():\n    with pytest.raises(RuntimeError) as e: f(2, 0)\n    assert str(e.value) == 'limit exceeded'\ndef test_seven(): assert f(7, 16) == [7, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1]\ndef test_seven_short():\n    with pytest.raises(RuntimeError): f(7, 15)\ndef test_bad_start_zero():\n    with pytest.raises(ValueError) as e: f(0, 5)\n    assert str(e.value) == 'bad start'\ndef test_bad_start_bool():\n    with pytest.raises(ValueError) as e: f(True, 5)\n    assert str(e.value) == 'bad start'\ndef test_bad_start_float():\n    with pytest.raises(ValueError) as e: f(1.0, 5)\n    assert str(e.value) == 'bad start'\ndef test_bad_limit():\n    with pytest.raises(ValueError) as e: f(5, -1)\n    assert str(e.value) == 'bad limit'\ndef test_bad_limit_bool():\n    with pytest.raises(ValueError) as e: f(5, True)\n    assert str(e.value) == 'bad limit'\ndef test_start_before_limit():\n    with pytest.raises(ValueError) as e: f(0, -1)\n    assert str(e.value) == 'bad start'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'knight_min_moves',
        "Write a Python function knight_moves(n, start, goal) that returns the minimum number of chess-knight moves needed to travel from start to goal on an n-by-n board, or -1 when the goal is unreachable. n must be an int, must not be a bool, and must be at least 1; otherwise -> ValueError('bad board'). start and goal must each be EXACTLY a tuple (not a list or any other sequence) of exactly two values (row, col), each an int and not a bool, each from 0 to n-1 inclusive; any violation -> ValueError('bad cell'). Validate n first, then start, then goal. A knight move jumps two squares along one axis and one square along the perpendicular axis, in any of the eight combinations; only the landing square must lie on the board. When start equals goal the answer is 0, even on a 1-by-1 board. On a board too small for any knight move every other square is unreachable, so the answer is -1. Output ONLY the function definition.",
        'solution.py',
        'def knight_moves(n, start, goal):\n    if not isinstance(n, int) or isinstance(n, bool) or n < 1:\n        raise ValueError("bad board")\n    for cell in (start, goal):\n        if type(cell) is not tuple or len(cell) != 2:\n            raise ValueError("bad cell")\n        for v in cell:\n            if not isinstance(v, int) or isinstance(v, bool):\n                raise ValueError("bad cell")\n            if v < 0 or v >= n:\n                raise ValueError("bad cell")\n    if start == goal:\n        return 0\n    deltas = ((1, 2), (2, 1), (2, -1), (1, -2),\n              (-1, -2), (-2, -1), (-2, 1), (-1, 2))\n    dist = {start: 0}\n    queue = [start]\n    head = 0\n    while head < len(queue):\n        r, c = queue[head]\n        head += 1\n        d = dist[(r, c)]\n        for dr, dc in deltas:\n            nr, nc = r + dr, c + dc\n            if 0 <= nr < n and 0 <= nc < n and (nr, nc) not in dist:\n                if (nr, nc) == goal:\n                    return d + 1\n                dist[(nr, nc)] = d + 1\n                queue.append((nr, nc))\n    return -1\n',
        "import pytest\nfrom solution import knight_moves as f\ndef test_one_move(): assert f(8, (0, 0), (1, 2)) == 1\ndef test_same_cell(): assert f(8, (4, 4), (4, 4)) == 0\ndef test_one_by_one(): assert f(1, (0, 0), (0, 0)) == 0\ndef test_corner_to_corner(): assert f(8, (0, 0), (7, 7)) == 6\ndef test_five_board(): assert f(5, (0, 0), (4, 4)) == 4\ndef test_three_corner(): assert f(3, (0, 0), (2, 2)) == 4\ndef test_center_isolated(): assert f(3, (1, 1), (0, 0)) == -1\ndef test_two_board_unreachable(): assert f(2, (0, 0), (1, 1)) == -1\ndef test_bad_board_zero():\n    with pytest.raises(ValueError) as e: f(0, (0, 0), (0, 0))\n    assert str(e.value) == 'bad board'\ndef test_bad_board_bool():\n    with pytest.raises(ValueError): f(True, (0, 0), (0, 0))\ndef test_bad_cell_list():\n    with pytest.raises(ValueError) as e: f(8, [0, 0], (0, 0))\n    assert str(e.value) == 'bad cell'\ndef test_bad_cell_range():\n    with pytest.raises(ValueError): f(8, (0, 0), (0, 8))\ndef test_bad_cell_bool():\n    with pytest.raises(ValueError): f(8, (0, True), (0, 0))\ndef test_bad_cell_len():\n    with pytest.raises(ValueError): f(8, (0, 0, 0), (0, 0))\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'grid_bfs_steps',
        "Write a Python function path_steps(grid) that returns the length in moves of the shortest path through a rectangular grid, or -1 when no path exists. grid must be a list with at least one row, and every row must be a list with at least one cell; otherwise -> ValueError('bad grid'). Every row must have the same length as the first row; otherwise -> ValueError('ragged'). Every cell must be the int 0 (open floor) or the int 1 (wall) and must not be a bool; otherwise -> ValueError('bad cell'). Perform those three checks in that order. The path starts at the top-left cell (row 0, column 0) and ends at the bottom-right cell, moving one cell up, down, left, or right at a time and only through open cells. Return the number of moves in the shortest such path. When the start cell or the goal cell is a wall, or no route exists, return -1. A 1-by-1 grid whose only cell is open returns 0. Output ONLY the function definition.",
        'solution.py',
        'def path_steps(grid):\n    if not isinstance(grid, list) or not grid:\n        raise ValueError("bad grid")\n    for row in grid:\n        if not isinstance(row, list) or not row:\n            raise ValueError("bad grid")\n    width = len(grid[0])\n    for row in grid:\n        if len(row) != width:\n            raise ValueError("ragged")\n    for row in grid:\n        for cell in row:\n            if not isinstance(cell, int) or isinstance(cell, bool) or cell not in (0, 1):\n                raise ValueError("bad cell")\n    rows, cols = len(grid), width\n    if grid[0][0] == 1 or grid[rows - 1][cols - 1] == 1:\n        return -1\n    if rows == 1 and cols == 1:\n        return 0\n    dist = [[-1] * cols for _ in range(rows)]\n    dist[0][0] = 0\n    queue = [(0, 0)]\n    head = 0\n    while head < len(queue):\n        r, c = queue[head]\n        head += 1\n        for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):\n            nr, nc = r + dr, c + dc\n            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 0 and dist[nr][nc] == -1:\n                dist[nr][nc] = dist[r][c] + 1\n                if nr == rows - 1 and nc == cols - 1:\n                    return dist[nr][nc]\n                queue.append((nr, nc))\n    return -1\n',
        "import pytest\nfrom solution import path_steps as f\ndef test_open_two(): assert f([[0, 0], [0, 0]]) == 2\ndef test_single_open(): assert f([[0]]) == 0\ndef test_single_wall(): assert f([[1]]) == -1\ndef test_blocked(): assert f([[0, 1], [1, 0]]) == -1\ndef test_detour(): assert f([[0, 0, 0], [1, 1, 0], [0, 0, 0]]) == 4\ndef test_row(): assert f([[0, 0, 0, 0]]) == 3\ndef test_start_wall(): assert f([[1, 0], [0, 0]]) == -1\ndef test_goal_wall(): assert f([[0, 0], [0, 1]]) == -1\ndef test_ragged():\n    with pytest.raises(ValueError) as e: f([[0, 0], [0]])\n    assert str(e.value) == 'ragged'\ndef test_ragged_before_cell():\n    with pytest.raises(ValueError) as e: f([[0, 2], [0]])\n    assert str(e.value) == 'ragged'\ndef test_bad_cell_two():\n    with pytest.raises(ValueError) as e: f([[0, 2]])\n    assert str(e.value) == 'bad cell'\ndef test_bad_cell_bool():\n    with pytest.raises(ValueError): f([[0, True]])\ndef test_bad_grid_empty():\n    with pytest.raises(ValueError) as e: f([])\n    assert str(e.value) == 'bad grid'\ndef test_bad_grid_empty_row():\n    with pytest.raises(ValueError): f([[]])\ndef test_bad_grid_not_list():\n    with pytest.raises(ValueError): f('grid')\ndef test_bad_grid_flat():\n    with pytest.raises(ValueError): f([0, 1])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'union_component_count',
        "Write a Python function component_count(n, edges) that returns the number of connected components of an undirected graph whose nodes are numbered 0 to n-1. n must be an int, must not be a bool, and must be at least 0; otherwise -> ValueError('bad n'). edges must be a list; otherwise -> ValueError('bad edges'). Every edge must be EXACTLY a tuple (not a list or any other sequence) of exactly two values, each an int and not a bool, each from 0 to n-1 inclusive; any violation -> ValueError('bad edge'). Validate n, then the edges container, then every edge, all before any counting. A self-loop edge and a duplicate edge are both legal and change nothing beyond connecting what they connect. With no edges the answer is n, and when n is 0 the answer is 0. Output ONLY the function definition.",
        'solution.py',
        'def component_count(n, edges):\n    if not isinstance(n, int) or isinstance(n, bool) or n < 0:\n        raise ValueError("bad n")\n    if not isinstance(edges, list):\n        raise ValueError("bad edges")\n    for e in edges:\n        if type(e) is not tuple or len(e) != 2:\n            raise ValueError("bad edge")\n        for v in e:\n            if not isinstance(v, int) or isinstance(v, bool) or v < 0 or v >= n:\n                raise ValueError("bad edge")\n    parent = list(range(n))\n\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]\n            x = parent[x]\n        return x\n\n    count = n\n    for a, b in edges:\n        ra, rb = find(a), find(b)\n        if ra != rb:\n            parent[ra] = rb\n            count -= 1\n    return count\n',
        "import pytest\nfrom solution import component_count as f\ndef test_no_edges(): assert f(5, []) == 5\ndef test_chain(): assert f(5, [(0, 1), (1, 2)]) == 3\ndef test_two_pairs(): assert f(4, [(0, 1), (2, 3)]) == 2\ndef test_duplicates(): assert f(3, [(0, 1), (0, 1), (1, 0)]) == 2\ndef test_self_loop(): assert f(3, [(1, 1)]) == 3\ndef test_zero_nodes(): assert f(0, []) == 0\ndef test_cycle(): assert f(4, [(0, 1), (1, 2), (2, 3), (3, 0)]) == 1\ndef test_bad_n_negative():\n    with pytest.raises(ValueError) as e: f(-1, [])\n    assert str(e.value) == 'bad n'\ndef test_bad_n_bool():\n    with pytest.raises(ValueError): f(True, [])\ndef test_bad_edges():\n    with pytest.raises(ValueError) as e: f(2, 'x')\n    assert str(e.value) == 'bad edges'\ndef test_bad_edge_list():\n    with pytest.raises(ValueError) as e: f(2, [[0, 1]])\n    assert str(e.value) == 'bad edge'\ndef test_bad_edge_len():\n    with pytest.raises(ValueError): f(2, [(0,)])\ndef test_bad_edge_range():\n    with pytest.raises(ValueError): f(2, [(0, 2)])\ndef test_bad_edge_bool():\n    with pytest.raises(ValueError): f(2, [(0, True)])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'bipartite_strict',
        "Write a Python function is_bipartite(adj) that reports whether an undirected graph is bipartite, returning a bool. adj is an adjacency list: adj[i] is the list of neighbors of node i. adj must be a list and every entry of adj must be a list; otherwise -> ValueError('bad adjacency'). Every neighbor must be an int, not a bool, from 0 to len(adj)-1 inclusive; otherwise -> ValueError('bad neighbor'). The listing must be symmetric: whenever j appears in adj[i], i must also appear in adj[j]; otherwise -> ValueError('not symmetric'). Run those three validations in that order, finishing each over the whole structure before starting the next, and only then decide bipartiteness. Duplicate neighbor entries are legal. The graph is bipartite when its nodes can be split into two sets so that every edge joins the two sets; the graph may be disconnected and every component must qualify. A self-loop (a node listed among its own neighbors) passes the symmetry check on its own but makes the graph NOT bipartite. The empty list is bipartite. Output ONLY the function definition.",
        'solution.py',
        'def is_bipartite(adj):\n    if not isinstance(adj, list):\n        raise ValueError("bad adjacency")\n    for row in adj:\n        if not isinstance(row, list):\n            raise ValueError("bad adjacency")\n    n = len(adj)\n    for row in adj:\n        for v in row:\n            if not isinstance(v, int) or isinstance(v, bool) or v < 0 or v >= n:\n                raise ValueError("bad neighbor")\n    for i in range(n):\n        for j in adj[i]:\n            if i not in adj[j]:\n                raise ValueError("not symmetric")\n    color = [None] * n\n    for s in range(n):\n        if color[s] is not None:\n            continue\n        color[s] = 0\n        queue = [s]\n        head = 0\n        while head < len(queue):\n            u = queue[head]\n            head += 1\n            for v in adj[u]:\n                if color[v] is None:\n                    color[v] = 1 - color[u]\n                    queue.append(v)\n                elif color[v] == color[u]:\n                    return False\n    return True\n',
        "import pytest\nfrom solution import is_bipartite as f\ndef test_empty(): assert f([]) is True\ndef test_single_edge(): assert f([[1], [0]]) is True\ndef test_triangle(): assert f([[1, 2], [0, 2], [0, 1]]) is False\ndef test_isolated(): assert f([[], [], []]) is True\ndef test_self_loop(): assert f([[0]]) is False\ndef test_even_cycle(): assert f([[1, 3], [0, 2], [1, 3], [2, 0]]) is True\ndef test_odd_component(): assert f([[1], [0], [3, 4], [2, 4], [2, 3]]) is False\ndef test_duplicate_neighbors(): assert f([[1, 1], [0]]) is True\ndef test_not_symmetric():\n    with pytest.raises(ValueError) as e: f([[1], []])\n    assert str(e.value) == 'not symmetric'\ndef test_bad_neighbor_range():\n    with pytest.raises(ValueError) as e: f([[5]])\n    assert str(e.value) == 'bad neighbor'\ndef test_bad_neighbor_bool():\n    with pytest.raises(ValueError): f([[True], [0]])\ndef test_bad_neighbor_negative():\n    with pytest.raises(ValueError): f([[-1]])\ndef test_bad_adjacency_not_list():\n    with pytest.raises(ValueError) as e: f('x')\n    assert str(e.value) == 'bad adjacency'\ndef test_bad_adjacency_entry():\n    with pytest.raises(ValueError): f([1])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'portal_min_moves',
        "Write a Python function portal_moves(n, portals, start, goal) that returns the minimum number of moves to travel between two cells of a one-dimensional board with one-way teleporters. The board has n cells numbered 0 to n-1. n must be an int, not a bool, and at least 1; otherwise -> ValueError('bad n'). start and goal must each be an int, not a bool, from 0 to n-1 inclusive; otherwise -> ValueError('bad cell'); check start before goal. portals must be a list, and every element must be EXACTLY a tuple (not a list) of exactly two values (entry, exit), each an int and not a bool, each from 0 to n-1 inclusive; any violation -> ValueError('bad portal'). If two portals share the same entry cell, including the same pair listed twice, -> ValueError('duplicate portal'). Validate n first, then start and goal, then the portals in order. One move goes from cell i to cell i-1 (when i-1 is at least 0), to cell i+1 (when i+1 is at most n-1), or, when i is a portal entry, to that portal's exit. Every move costs exactly 1 and portals are one-way: standing on an exit does not allow jumping back. When start equals goal the answer is 0. The goal is always reachable by unit steps, so the function always returns an int. Output ONLY the function definition.",
        'solution.py',
        'def portal_moves(n, portals, start, goal):\n    if not isinstance(n, int) or isinstance(n, bool) or n < 1:\n        raise ValueError("bad n")\n    for cell in (start, goal):\n        if not isinstance(cell, int) or isinstance(cell, bool) or cell < 0 or cell >= n:\n            raise ValueError("bad cell")\n    if not isinstance(portals, list):\n        raise ValueError("bad portal")\n    jump = {}\n    for p in portals:\n        if type(p) is not tuple or len(p) != 2:\n            raise ValueError("bad portal")\n        for v in p:\n            if not isinstance(v, int) or isinstance(v, bool) or v < 0 or v >= n:\n                raise ValueError("bad portal")\n        if p[0] in jump:\n            raise ValueError("duplicate portal")\n        jump[p[0]] = p[1]\n    if start == goal:\n        return 0\n    dist = [-1] * n\n    dist[start] = 0\n    queue = [start]\n    head = 0\n    while head < len(queue):\n        u = queue[head]\n        head += 1\n        nxts = []\n        if u - 1 >= 0:\n            nxts.append(u - 1)\n        if u + 1 < n:\n            nxts.append(u + 1)\n        if u in jump:\n            nxts.append(jump[u])\n        for v in nxts:\n            if dist[v] == -1:\n                dist[v] = dist[u] + 1\n                if v == goal:\n                    return dist[v]\n                queue.append(v)\n    return dist[goal]\n',
        "import pytest\nfrom solution import portal_moves as f\ndef test_plain_walk(): assert f(10, [], 0, 9) == 9\ndef test_direct_portal(): assert f(10, [(0, 9)], 0, 9) == 1\ndef test_walk_then_portal(): assert f(10, [(1, 8)], 0, 9) == 3\ndef test_same_cell(): assert f(5, [], 3, 3) == 0\ndef test_one_cell(): assert f(1, [], 0, 0) == 0\ndef test_backward_portal_useless(): assert f(10, [(9, 0)], 0, 9) == 9\ndef test_one_way(): assert f(10, [(0, 5)], 5, 0) == 5\ndef test_self_portal(): assert f(6, [(2, 2)], 0, 5) == 5\ndef test_best_of_two(): assert f(10, [(3, 9), (1, 7)], 0, 9) == 4\ndef test_duplicate_entry():\n    with pytest.raises(ValueError) as e: f(10, [(1, 2), (1, 3)], 0, 9)\n    assert str(e.value) == 'duplicate portal'\ndef test_duplicate_identical():\n    with pytest.raises(ValueError) as e: f(10, [(1, 2), (1, 2)], 0, 9)\n    assert str(e.value) == 'duplicate portal'\ndef test_bad_portal_list():\n    with pytest.raises(ValueError) as e: f(10, [[1, 2]], 0, 9)\n    assert str(e.value) == 'bad portal'\ndef test_bad_portal_range():\n    with pytest.raises(ValueError): f(10, [(1, 10)], 0, 9)\ndef test_bad_portal_bool():\n    with pytest.raises(ValueError): f(10, [(1, True)], 0, 9)\ndef test_bad_portal_not_list():\n    with pytest.raises(ValueError): f(10, 'x', 0, 9)\ndef test_bad_n():\n    with pytest.raises(ValueError) as e: f(0, [], 0, 0)\n    assert str(e.value) == 'bad n'\ndef test_bad_n_bool():\n    with pytest.raises(ValueError): f(True, [], 0, 0)\ndef test_bad_cell_range():\n    with pytest.raises(ValueError) as e: f(5, [], 5, 0)\n    assert str(e.value) == 'bad cell'\ndef test_bad_cell_bool():\n    with pytest.raises(ValueError): f(5, [], True, 0)\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'spread_radius',
        "Write a Python function spread_radius(grid) that computes how many steps a signal needs to spread from its sources to cover a grid. grid must be a list with at least one row, and every row must be a str with at least one character; otherwise -> ValueError('bad grid'). Every row must have the same length as the first row; otherwise -> ValueError('ragged'). Every character must be one of: the uppercase letter S (a source), the period (open floor), or the hash sign (a wall); otherwise -> ValueError('bad cell'). The grid must contain at least one S; otherwise -> ValueError('no source'). Perform those four checks in that order. The signal starts at every source at time 0 and each step spreads one cell up, down, left, and right into cells that are not walls. Return the largest number of steps needed for the signal to first reach an open-floor cell, that is, the maximum over all open cells of the distance to the nearest source. When some open cell can never be reached return -1. When the grid has no open-floor cells at all return 0. Output ONLY the function definition.",
        'solution.py',
        'def spread_radius(grid):\n    if not isinstance(grid, list) or not grid:\n        raise ValueError("bad grid")\n    for row in grid:\n        if not isinstance(row, str) or row == "":\n            raise ValueError("bad grid")\n    width = len(grid[0])\n    for row in grid:\n        if len(row) != width:\n            raise ValueError("ragged")\n    for row in grid:\n        for ch in row:\n            if ch not in "S.#":\n                raise ValueError("bad cell")\n    rows, cols = len(grid), width\n    dist = [[-1] * cols for _ in range(rows)]\n    queue = []\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == "S":\n                dist[r][c] = 0\n                queue.append((r, c))\n    if not queue:\n        raise ValueError("no source")\n    head = 0\n    while head < len(queue):\n        r, c = queue[head]\n        head += 1\n        for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):\n            nr, nc = r + dr, c + dc\n            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] != "#" and dist[nr][nc] == -1:\n                dist[nr][nc] = dist[r][c] + 1\n                queue.append((nr, nc))\n    best = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == ".":\n                if dist[r][c] == -1:\n                    return -1\n                if dist[r][c] > best:\n                    best = dist[r][c]\n    return best\n',
        "import pytest\nfrom solution import spread_radius as f\ndef test_one_step(): assert f(['S.']) == 1\ndef test_source_only(): assert f(['S']) == 0\ndef test_unreachable(): assert f(['S#.']) == -1\ndef test_square(): assert f(['S..', '...', '...']) == 4\ndef test_two_sources(): assert f(['S.S']) == 1\ndef test_two_sources_middle(): assert f(['S...S']) == 2\ndef test_corridor(): assert f(['S..', '##.', '...']) == 6\ndef test_no_open_cells(): assert f(['S#']) == 0\ndef test_ragged():\n    with pytest.raises(ValueError) as e: f(['S.', 'S'])\n    assert str(e.value) == 'ragged'\ndef test_bad_cell():\n    with pytest.raises(ValueError) as e: f(['SX'])\n    assert str(e.value) == 'bad cell'\ndef test_no_source():\n    with pytest.raises(ValueError) as e: f(['...'])\n    assert str(e.value) == 'no source'\ndef test_bad_grid_plain_string():\n    with pytest.raises(ValueError) as e: f('S.')\n    assert str(e.value) == 'bad grid'\ndef test_bad_grid_empty():\n    with pytest.raises(ValueError): f([])\ndef test_bad_grid_empty_row():\n    with pytest.raises(ValueError): f([''])\ndef test_bad_grid_row_type():\n    with pytest.raises(ValueError): f([1])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'lru_trace',
        "Write a Python function lru_trace(capacity, ops) that simulates an LRU cache and returns the list of results of the get operations, in order. capacity must be an int, must not be a bool, and must be at least 1; otherwise -> ValueError('bad capacity'). Each element of ops must be EXACTLY a tuple of the form ('get', key) with exactly two items or ('put', key, value) with exactly three items; any other element (wrong type, wrong length, or an unknown first item) -> ValueError('bad op'), raised when that element is reached in left-to-right processing. A get of a present key appends its value to the result list and makes that key the most recently used. A get of a missing key appends None and leaves the recency order unchanged. A put of an existing key replaces its value and makes it the most recently used, never evicting. A put of a new key when the cache already holds capacity keys first evicts the least recently used key, then inserts. Only get operations append to the returned list. Output ONLY the function definition.",
        'solution.py',
        'def lru_trace(capacity, ops):\n    if not isinstance(capacity, int) or isinstance(capacity, bool) or capacity < 1:\n        raise ValueError("bad capacity")\n    cache = {}\n    out = []\n    for op in ops:\n        if type(op) is not tuple or len(op) < 1:\n            raise ValueError("bad op")\n        if op[0] == "get" and len(op) == 2:\n            key = op[1]\n            if key in cache:\n                val = cache.pop(key)\n                cache[key] = val\n                out.append(val)\n            else:\n                out.append(None)\n        elif op[0] == "put" and len(op) == 3:\n            key, val = op[1], op[2]\n            if key in cache:\n                cache.pop(key)\n            elif len(cache) >= capacity:\n                cache.pop(next(iter(cache)))\n            cache[key] = val\n        else:\n            raise ValueError("bad op")\n    return out\n',
        "import pytest\nfrom solution import lru_trace as f\ndef test_basic_eviction():\n    assert f(2, [('put', 'a', 1), ('put', 'b', 2), ('put', 'c', 3), ('get', 'a'), ('get', 'b'), ('get', 'c')]) == [None, 2, 3]\ndef test_get_refreshes():\n    assert f(2, [('put', 'a', 1), ('put', 'b', 2), ('get', 'a'), ('put', 'c', 3), ('get', 'b'), ('get', 'a'), ('get', 'c')]) == [1, None, 1, 3]\ndef test_put_updates_no_evict():\n    assert f(2, [('put', 'a', 1), ('put', 'b', 2), ('put', 'a', 9), ('put', 'c', 3), ('get', 'a'), ('get', 'b'), ('get', 'c')]) == [9, None, 3]\ndef test_miss_no_recency():\n    assert f(2, [('put', 'a', 1), ('put', 'b', 2), ('get', 'zz'), ('put', 'c', 3), ('get', 'a'), ('get', 'b')]) == [None, None, 2]\ndef test_capacity_one():\n    assert f(1, [('put', 'a', 1), ('put', 'b', 2), ('get', 'a'), ('get', 'b')]) == [None, 2]\ndef test_empty_ops():\n    assert f(3, []) == []\ndef test_bad_capacity_zero():\n    with pytest.raises(ValueError) as e: f(0, [])\n    assert str(e.value) == 'bad capacity'\ndef test_bad_capacity_bool():\n    with pytest.raises(ValueError): f(True, [])\ndef test_bad_op_shape():\n    with pytest.raises(ValueError) as e: f(2, [('get', 'a', 'b')])\n    assert str(e.value) == 'bad op'\ndef test_bad_op_name():\n    with pytest.raises(ValueError): f(2, [('del', 'a')])\ndef test_bad_op_list():\n    with pytest.raises(ValueError): f(2, [['get', 'a']])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'min_stack_trace',
        "Write a Python function min_stack(ops) that simulates a stack with minimum tracking and returns the list of outputs, in order. ops must be a list; otherwise -> ValueError('bad ops'). Each element must be EXACTLY one of these tuples: ('push', v) with exactly two items where v is an int and not a bool; ('pop',), ('top',), or ('min',), each with exactly one item. Any other element -> ValueError('bad op'), raised when that element is reached in left-to-right processing. push adds v to the top of the stack and produces no output. pop removes the top value and appends it to the output list. top appends the top value without removing it. min appends the smallest value currently on the stack, leaving the stack unchanged. pop, top, and min on an empty stack each -> ValueError('empty stack'). Output ONLY the function definition.",
        'solution.py',
        'def min_stack(ops):\n    if not isinstance(ops, list):\n        raise ValueError("bad ops")\n    stack = []\n    out = []\n    for op in ops:\n        if type(op) is not tuple or len(op) < 1:\n            raise ValueError("bad op")\n        if (op[0] == "push" and len(op) == 2 and isinstance(op[1], int)\n                and not isinstance(op[1], bool)):\n            stack.append(op[1])\n        elif op == ("pop",):\n            if not stack:\n                raise ValueError("empty stack")\n            out.append(stack.pop())\n        elif op == ("top",):\n            if not stack:\n                raise ValueError("empty stack")\n            out.append(stack[-1])\n        elif op == ("min",):\n            if not stack:\n                raise ValueError("empty stack")\n            out.append(min(stack))\n        else:\n            raise ValueError("bad op")\n    return out\n',
        "import pytest\nfrom solution import min_stack as f\ndef test_trace():\n    assert f([('push', 3), ('push', 1), ('min',), ('push', 2), ('min',), ('top',), ('pop',), ('min',), ('pop',), ('min',)]) == [1, 1, 2, 2, 1, 1, 3]\ndef test_empty_ops():\n    assert f([]) == []\ndef test_negative():\n    assert f([('push', 5), ('push', -2), ('min',), ('pop',), ('min',)]) == [-2, -2, 5]\ndef test_duplicate_min():\n    assert f([('push', 1), ('push', 1), ('pop',), ('min',)]) == [1, 1]\ndef test_pop_empty():\n    with pytest.raises(ValueError) as e: f([('pop',)])\n    assert str(e.value) == 'empty stack'\ndef test_min_empty():\n    with pytest.raises(ValueError) as e: f([('min',)])\n    assert str(e.value) == 'empty stack'\ndef test_top_empty():\n    with pytest.raises(ValueError): f([('top',)])\ndef test_push_bool():\n    with pytest.raises(ValueError) as e: f([('push', True)])\n    assert str(e.value) == 'bad op'\ndef test_push_missing_arg():\n    with pytest.raises(ValueError): f([('push',)])\ndef test_bad_ops():\n    with pytest.raises(ValueError) as e: f('nope')\n    assert str(e.value) == 'bad ops'\ndef test_unknown_op():\n    with pytest.raises(ValueError): f([('peek',)])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'ring_buffer_trace',
        "Write a Python function ring_buffer(capacity, ops) that simulates a circular buffer that overwrites its oldest element when full, and returns the list of outputs, in order. capacity must be an int, not a bool, and at least 1; otherwise -> ValueError('bad capacity'). Each element of ops must be EXACTLY a tuple ('write', v) with exactly two items, or ('read',) or ('peek',) with exactly one item; anything else -> ValueError('bad op'), raised when that element is reached in left-to-right processing. write appends v at the newest end; when the buffer already holds capacity elements the oldest element is dropped to make room, and write appends the dropped element to the output list, otherwise write appends None. read removes the oldest element and appends it to the output list. peek appends the oldest element without removing it. read and peek on an empty buffer each -> ValueError('buffer empty'). Every operation appends exactly one entry to the output list. Output ONLY the function definition.",
        'solution.py',
        'def ring_buffer(capacity, ops):\n    if not isinstance(capacity, int) or isinstance(capacity, bool) or capacity < 1:\n        raise ValueError("bad capacity")\n    buf = []\n    out = []\n    for op in ops:\n        if type(op) is not tuple or len(op) < 1:\n            raise ValueError("bad op")\n        if op[0] == "write" and len(op) == 2:\n            if len(buf) >= capacity:\n                out.append(buf.pop(0))\n            else:\n                out.append(None)\n            buf.append(op[1])\n        elif op == ("read",):\n            if not buf:\n                raise ValueError("buffer empty")\n            out.append(buf.pop(0))\n        elif op == ("peek",):\n            if not buf:\n                raise ValueError("buffer empty")\n            out.append(buf[0])\n        else:\n            raise ValueError("bad op")\n    return out\n',
        "import pytest\nfrom solution import ring_buffer as f\ndef test_overwrite():\n    assert f(2, [('write', 1), ('write', 2), ('write', 3), ('read',), ('read',)]) == [None, None, 1, 2, 3]\ndef test_peek():\n    assert f(3, [('write', 7), ('peek',), ('read',)]) == [None, 7, 7]\ndef test_capacity_one():\n    assert f(1, [('write', 1), ('write', 2), ('read',)]) == [None, 1, 2]\ndef test_fifo_order():\n    assert f(3, [('write', 1), ('write', 2), ('read',), ('write', 3), ('read',), ('read',)]) == [None, None, 1, None, 2, 3]\ndef test_empty_ops():\n    assert f(2, []) == []\ndef test_read_empty():\n    with pytest.raises(ValueError) as e: f(2, [('read',)])\n    assert str(e.value) == 'buffer empty'\ndef test_peek_empty():\n    with pytest.raises(ValueError): f(2, [('peek',)])\ndef test_read_after_drain():\n    with pytest.raises(ValueError): f(2, [('write', 1), ('read',), ('read',)])\ndef test_bad_capacity():\n    with pytest.raises(ValueError) as e: f(0, [])\n    assert str(e.value) == 'bad capacity'\ndef test_bad_capacity_bool():\n    with pytest.raises(ValueError): f(True, [])\ndef test_bad_op():\n    with pytest.raises(ValueError) as e: f(2, [('write',)])\n    assert str(e.value) == 'bad op'\ndef test_bad_op_unknown():\n    with pytest.raises(ValueError): f(2, [('pop',)])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'k_smallest_names',
        "Write a Python function k_smallest(records, k) that returns the names of the k lowest-scoring records. Validate k first: it must be an int, not a bool, and at least 0; otherwise -> ValueError('bad k'). Then scan records left to right: each element must be EXACTLY a tuple of exactly two items (name, score) where name is a str and score is an int and not a bool; any other element -> ValueError('bad record'). A name equal to the name of an earlier record -> ValueError('duplicate name'). Rank the records by ascending score, breaking ties by ascending lexicographic (ASCII) order of name, and return a list of just the names of the first k records in that ranking. When k is 0 return the empty list; when k exceeds the number of records return all names in ranked order (never pad and never repeat). Output ONLY the function definition.",
        'solution.py',
        'def k_smallest(records, k):\n    if not isinstance(k, int) or isinstance(k, bool) or k < 0:\n        raise ValueError("bad k")\n    seen = set()\n    for r in records:\n        if type(r) is not tuple or len(r) != 2:\n            raise ValueError("bad record")\n        name, score = r\n        if (not isinstance(name, str) or not isinstance(score, int)\n                or isinstance(score, bool)):\n            raise ValueError("bad record")\n        if name in seen:\n            raise ValueError("duplicate name")\n        seen.add(name)\n    ranked = sorted(records, key=lambda r: (r[1], r[0]))\n    return [name for name, _ in ranked[:k]]\n',
        "import pytest\nfrom solution import k_smallest as f\ndef test_basic():\n    assert f([('a', 3), ('b', 1), ('c', 2)], 2) == ['b', 'c']\ndef test_tie_break():\n    assert f([('z', 1), ('a', 1), ('m', 0)], 2) == ['m', 'a']\ndef test_k_zero():\n    assert f([('a', 1)], 0) == []\ndef test_k_exceeds():\n    assert f([('b', 2), ('a', 1)], 9) == ['a', 'b']\ndef test_empty():\n    assert f([], 3) == []\ndef test_negative_scores():\n    assert f([('a', -1), ('b', -5)], 1) == ['b']\ndef test_duplicate_name():\n    with pytest.raises(ValueError) as e: f([('a', 1), ('a', 2)], 1)\n    assert str(e.value) == 'duplicate name'\ndef test_bad_record_list():\n    with pytest.raises(ValueError) as e: f([['a', 1]], 1)\n    assert str(e.value) == 'bad record'\ndef test_bad_record_bool_score():\n    with pytest.raises(ValueError): f([('a', True)], 1)\ndef test_bad_record_len():\n    with pytest.raises(ValueError): f([('a', 1, 2)], 1)\ndef test_bad_k_bool():\n    with pytest.raises(ValueError) as e: f([], True)\n    assert str(e.value) == 'bad k'\ndef test_bad_k_negative():\n    with pytest.raises(ValueError): f([], -1)\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'bank_ledger',
        "Write a Python function bank_ledger(ops) that folds a list of banking operations over a balance that starts at 0 and returns the list of balances after each operation, in order. Each element of ops must be EXACTLY a tuple of exactly two items ('deposit', amount) or ('withdraw', amount); any other element -> ValueError('bad op'), raised when that element is reached in left-to-right processing. The op-shape check happens first; then amount must be an int, not a bool, and at least 1, otherwise -> ValueError('bad amount'). deposit adds amount to the balance. withdraw subtracts amount, but when amount exceeds the current balance it raises ValueError with EXACTLY the message 'insufficient funds: need N have B' where N is the decimal amount and B is the decimal current balance (for example withdrawing 50 from a balance of 30 raises ValueError('insufficient funds: need 50 have 30')). Withdrawing an amount exactly equal to the balance is allowed and leaves 0. After each successful operation the new balance is appended to the returned list. The empty list returns the empty list. Output ONLY the function definition.",
        'solution.py',
        'def bank_ledger(ops):\n    balance = 0\n    out = []\n    for op in ops:\n        if (type(op) is not tuple or len(op) != 2\n                or op[0] not in ("deposit", "withdraw")):\n            raise ValueError("bad op")\n        kind, amount = op\n        if not isinstance(amount, int) or isinstance(amount, bool) or amount < 1:\n            raise ValueError("bad amount")\n        if kind == "deposit":\n            balance += amount\n        else:\n            if amount > balance:\n                raise ValueError(\n                    "insufficient funds: need %d have %d" % (amount, balance))\n            balance -= amount\n        out.append(balance)\n    return out\n',
        "import pytest\nfrom solution import bank_ledger as f\ndef test_basic():\n    assert f([('deposit', 100), ('withdraw', 30), ('deposit', 5)]) == [100, 70, 75]\ndef test_empty():\n    assert f([]) == []\ndef test_withdraw_all():\n    assert f([('deposit', 10), ('withdraw', 10)]) == [10, 0]\ndef test_insufficient_message():\n    with pytest.raises(ValueError) as e:\n        f([('deposit', 30), ('withdraw', 50)])\n    assert str(e.value) == 'insufficient funds: need 50 have 30'\ndef test_insufficient_zero():\n    with pytest.raises(ValueError) as e:\n        f([('withdraw', 1)])\n    assert str(e.value) == 'insufficient funds: need 1 have 0'\ndef test_bad_amount_zero():\n    with pytest.raises(ValueError) as e: f([('deposit', 0)])\n    assert str(e.value) == 'bad amount'\ndef test_bad_amount_bool():\n    with pytest.raises(ValueError): f([('deposit', True)])\ndef test_bad_amount_negative():\n    with pytest.raises(ValueError): f([('withdraw', -5)])\ndef test_bad_op_shape():\n    with pytest.raises(ValueError) as e: f([('deposit',)])\n    assert str(e.value) == 'bad op'\ndef test_bad_op_kind():\n    with pytest.raises(ValueError): f([('transfer', 5)])\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'inventory_reserve',
        "Write a Python function reserve_trace(stock, ops) that folds inventory reservation operations and returns the final reservations. stock must be a dict whose every key is a str and whose every value is an int, not a bool, and at least 0; any violation -> ValueError('bad stock'), and the input dict must never be mutated. Each element of ops must be EXACTLY a tuple of exactly three items ('reserve', item, qty) or ('cancel', item, qty); any other element -> ValueError('bad op'). Per element, in this order: the shape check above; then qty must be an int, not a bool, and at least 1, otherwise -> ValueError('bad qty'); then item must be a key of stock, otherwise -> ValueError('unknown item'). reserve increases the item's reserved count by qty, but when qty exceeds the item's available count (its stock value minus its current reserved count) it raises ValueError with EXACTLY the message 'not enough ' followed by the item name. cancel decreases the item's reserved count by qty; when qty exceeds the current reserved count -> ValueError('over-cancel'). Reserving exactly the available count and cancelling exactly the reserved count are both allowed. Return a list of (item, reserved) tuples for every item whose final reserved count is greater than 0, sorted by ascending item name. Output ONLY the function definition.",
        'solution.py',
        'def reserve_trace(stock, ops):\n    if not isinstance(stock, dict):\n        raise ValueError("bad stock")\n    for key, val in stock.items():\n        if not isinstance(key, str):\n            raise ValueError("bad stock")\n        if not isinstance(val, int) or isinstance(val, bool) or val < 0:\n            raise ValueError("bad stock")\n    reserved = {}\n    for op in ops:\n        if (type(op) is not tuple or len(op) != 3\n                or op[0] not in ("reserve", "cancel")):\n            raise ValueError("bad op")\n        kind, item, qty = op\n        if not isinstance(qty, int) or isinstance(qty, bool) or qty < 1:\n            raise ValueError("bad qty")\n        if item not in stock:\n            raise ValueError("unknown item")\n        cur = reserved.get(item, 0)\n        if kind == "reserve":\n            if qty > stock[item] - cur:\n                raise ValueError("not enough " + item)\n            reserved[item] = cur + qty\n        else:\n            if qty > cur:\n                raise ValueError("over-cancel")\n            reserved[item] = cur - qty\n    return sorted((it, n) for it, n in reserved.items() if n > 0)\n',
        "import pytest\nfrom solution import reserve_trace as f\ndef test_basic():\n    assert f({'w': 5}, [('reserve', 'w', 2)]) == [('w', 2)]\ndef test_accumulate_and_sort():\n    assert f({'b': 4, 'a': 4}, [('reserve', 'b', 1), ('reserve', 'a', 2), ('reserve', 'b', 1)]) == [('a', 2), ('b', 2)]\ndef test_cancel_to_zero_excluded():\n    assert f({'w': 5}, [('reserve', 'w', 3), ('cancel', 'w', 3)]) == []\ndef test_reserve_exactly_available():\n    assert f({'w': 5}, [('reserve', 'w', 5)]) == [('w', 5)]\ndef test_no_ops():\n    assert f({'w': 1}, []) == []\ndef test_not_enough_message():\n    with pytest.raises(ValueError) as e:\n        f({'widget': 3}, [('reserve', 'widget', 2), ('reserve', 'widget', 2)])\n    assert str(e.value) == 'not enough widget'\ndef test_over_cancel():\n    with pytest.raises(ValueError) as e:\n        f({'w': 5}, [('reserve', 'w', 1), ('cancel', 'w', 2)])\n    assert str(e.value) == 'over-cancel'\ndef test_unknown_item():\n    with pytest.raises(ValueError) as e: f({'w': 1}, [('reserve', 'x', 1)])\n    assert str(e.value) == 'unknown item'\ndef test_bad_qty_zero():\n    with pytest.raises(ValueError) as e: f({'w': 1}, [('reserve', 'w', 0)])\n    assert str(e.value) == 'bad qty'\ndef test_bad_qty_bool():\n    with pytest.raises(ValueError): f({'w': 1}, [('reserve', 'w', True)])\ndef test_bad_op():\n    with pytest.raises(ValueError) as e: f({'w': 1}, [('reserve', 'w')])\n    assert str(e.value) == 'bad op'\ndef test_bad_stock_bool_value():\n    with pytest.raises(ValueError) as e: f({'w': True}, [])\n    assert str(e.value) == 'bad stock'\ndef test_bad_stock_negative():\n    with pytest.raises(ValueError): f({'w': -1}, [])\ndef test_no_mutation():\n    s = {'w': 5}\n    f(s, [('reserve', 'w', 2)])\n    assert s == {'w': 5}\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'url_split_strict',
        "Write a Python function split_url(url) that splits a URL string into a tuple (scheme, host, port, path, query). url must be a str; otherwise -> ValueError('bad url'). The scheme is everything before the FIRST occurrence of the three-character separator colon slash slash; if that separator does not appear anywhere -> ValueError('no scheme'). The scheme must be non-empty, its first character must be a lowercase ASCII letter, and every following character must be a lowercase ASCII letter, an ASCII digit, a plus sign, a hyphen, or a dot; otherwise -> ValueError('bad scheme'). After the separator, the authority runs up to the first slash or question mark (or the end of the string). Within the authority, an optional port is introduced by the first colon; the part before that colon is the host. The host must be non-empty and contain only lowercase ASCII letters, ASCII digits, hyphens, and dots; otherwise -> ValueError('bad host'). When a colon is present, the port text must be one or more ASCII digits with no leading zero (a lone 0 is allowed) and its value must be at most 65535; anything else, including an empty port or a second colon in the authority, -> ValueError('bad port'). The port element of the tuple is that value as an int, or None when there is no colon. The path is the slash that ends the authority plus everything up to the first question mark; when the authority is followed by no slash the path is the single character /. The query is everything after the FIRST question mark (later question marks stay inside the query); it is the empty string for a trailing question mark and None when there is no question mark at all. Output ONLY the function definition.",
        'solution.py',
        'def split_url(url):\n    if not isinstance(url, str):\n        raise ValueError("bad url")\n    idx = url.find("://")\n    if idx == -1:\n        raise ValueError("no scheme")\n    scheme = url[:idx]\n    if scheme == "" or not ("a" <= scheme[0] <= "z"):\n        raise ValueError("bad scheme")\n    for ch in scheme[1:]:\n        if not ("a" <= ch <= "z" or "0" <= ch <= "9" or ch in "+-."):\n            raise ValueError("bad scheme")\n    rest = url[idx + 3:]\n    end = len(rest)\n    for i, ch in enumerate(rest):\n        if ch in "/?":\n            end = i\n            break\n    authority = rest[:end]\n    tail = rest[end:]\n    host, sep, port_s = authority.partition(":")\n    if host == "":\n        raise ValueError("bad host")\n    for ch in host:\n        if not ("a" <= ch <= "z" or "0" <= ch <= "9" or ch in "-."):\n            raise ValueError("bad host")\n    if sep:\n        if port_s == "" or not all("0" <= c <= "9" for c in port_s):\n            raise ValueError("bad port")\n        if len(port_s) > 1 and port_s[0] == "0":\n            raise ValueError("bad port")\n        port = int(port_s)\n        if port > 65535:\n            raise ValueError("bad port")\n    else:\n        port = None\n    if tail.startswith("/"):\n        q = tail.find("?")\n        if q == -1:\n            path, query = tail, None\n        else:\n            path, query = tail[:q], tail[q + 1:]\n    elif tail.startswith("?"):\n        path, query = "/", tail[1:]\n    else:\n        path, query = "/", None\n    return (scheme, host, port, path, query)\n',
        "import pytest\nfrom solution import split_url as f\ndef test_basic(): assert f('http://example.com/a/b?x=1') == ('http', 'example.com', None, '/a/b', 'x=1')\ndef test_no_path(): assert f('http://example.com') == ('http', 'example.com', None, '/', None)\ndef test_port(): assert f('https://a.b:8080/x') == ('https', 'a.b', 8080, '/x', None)\ndef test_query_no_path(): assert f('ftp://h?x=2') == ('ftp', 'h', None, '/', 'x=2')\ndef test_empty_query(): assert f('http://h/p?') == ('http', 'h', None, '/p', '')\ndef test_second_qmark(): assert f('http://h/p?a?b') == ('http', 'h', None, '/p', 'a?b')\ndef test_port_zero(): assert f('http://h:0/') == ('http', 'h', 0, '/', None)\ndef test_max_port(): assert f('http://h:65535') == ('http', 'h', 65535, '/', None)\ndef test_scheme_chars(): assert f('a+b-c.1://h') == ('a+b-c.1', 'h', None, '/', None)\ndef test_no_scheme():\n    with pytest.raises(ValueError) as e: f('example.com/a')\n    assert str(e.value) == 'no scheme'\ndef test_bad_scheme_upper():\n    with pytest.raises(ValueError) as e: f('Http://h')\n    assert str(e.value) == 'bad scheme'\ndef test_bad_scheme_empty():\n    with pytest.raises(ValueError): f('://h')\ndef test_bad_scheme_digit_first():\n    with pytest.raises(ValueError): f('1ab://h')\ndef test_bad_host_empty():\n    with pytest.raises(ValueError) as e: f('http://')\n    assert str(e.value) == 'bad host'\ndef test_bad_host_upper():\n    with pytest.raises(ValueError): f('http://EXample.com')\ndef test_bad_port_leading_zero():\n    with pytest.raises(ValueError) as e: f('http://h:080')\n    assert str(e.value) == 'bad port'\ndef test_bad_port_too_big():\n    with pytest.raises(ValueError): f('http://h:65536')\ndef test_bad_port_empty():\n    with pytest.raises(ValueError): f('http://h:')\ndef test_bad_port_second_colon():\n    with pytest.raises(ValueError): f('http://h:1:2')\ndef test_bad_url():\n    with pytest.raises(ValueError) as e: f(5)\n    assert str(e.value) == 'bad url'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'qp_decode',
        "Write a Python function qp_decode(s) that decodes a quoted-printable style string and returns the decoded str. s must be a str; otherwise -> ValueError('bad input'). Scan left to right. An equals sign starts an escape and is never emitted literally. An equals sign followed by exactly two uppercase hexadecimal digits (0-9 and A-F only) decodes to the single character whose code point is that two-digit hex value. An equals sign followed immediately by a line feed, or by a carriage return then a line feed, is a soft line break: the equals sign and that line ending are deleted and contribute nothing to the output. Any other use of the equals sign, including lowercase hex digits, fewer than two characters remaining before the end of the string, a carriage return not followed by a line feed, or any non-hex character in the two positions after the equals sign, raises ValueError('bad escape'). Every character other than the equals sign, including bare line feeds not preceded by an equals sign, passes through unchanged. The empty string decodes to the empty string. Output ONLY the function definition.",
        'solution.py',
        'def qp_decode(s):\n    if not isinstance(s, str):\n        raise ValueError("bad input")\n    out = []\n    i, n = 0, len(s)\n    while i < n:\n        ch = s[i]\n        if ch != "=":\n            out.append(ch)\n            i += 1\n            continue\n        if i + 1 < n and s[i + 1] == "\\n":\n            i += 2\n            continue\n        if i + 2 < n and s[i + 1] == "\\r" and s[i + 2] == "\\n":\n            i += 3\n            continue\n        if i + 2 < n:\n            h = s[i + 1:i + 3]\n            if all(c in "0123456789ABCDEF" for c in h):\n                out.append(chr(int(h, 16)))\n                i += 3\n                continue\n        raise ValueError("bad escape")\n    return "".join(out)\n',
        "import pytest\nfrom solution import qp_decode as f\ndef test_plain(): assert f('hello world') == 'hello world'\ndef test_space(): assert f('a=20b') == 'a b'\ndef test_equals(): assert f('=3D') == '='\ndef test_letters(): assert f('=41=42') == 'AB'\ndef test_soft_lf(): assert f('foo=\\nbar') == 'foobar'\ndef test_soft_crlf(): assert f('foo=\\r\\nbar') == 'foobar'\ndef test_hard_newline(): assert f('a\\nb') == 'a\\nb'\ndef test_high_byte(): assert f('=FF') == '\\xff'\ndef test_newline_escape(): assert f('=0A') == '\\n'\ndef test_empty(): assert f('') == ''\ndef test_lowercase():\n    with pytest.raises(ValueError) as e: f('=3d')\n    assert str(e.value) == 'bad escape'\ndef test_trailing():\n    with pytest.raises(ValueError) as e: f('abc=')\n    assert str(e.value) == 'bad escape'\ndef test_one_digit():\n    with pytest.raises(ValueError): f('=4')\ndef test_bad_hex():\n    with pytest.raises(ValueError): f('=G1')\ndef test_cr_only():\n    with pytest.raises(ValueError): f('a=\\rb')\ndef test_bad_input():\n    with pytest.raises(ValueError) as e: f(5)\n    assert str(e.value) == 'bad input'\n",
        'hard', max_new_tokens=512),
    TaskSpec(
        'ini_section_parse',
        "Write a Python function parse_ini(text) that parses a sectioned INI document into a dict mapping each section name to a dict of its keys to values. text must be a str; otherwise -> ValueError('bad input'). Split the text on line feeds and process each line after stripping leading and trailing spaces and tabs. A stripped line that is empty, or whose first character is a semicolon or a hash, is skipped as blank or comment. A stripped line whose first character is an opening square bracket is a section header: it must also end with a closing square bracket, and the name between the brackets must be non-empty and made only of ASCII letters, ASCII digits, and underscores; any violation -> ValueError('bad section'). A section name that has already appeared -> ValueError('duplicate section'); a new section starts as an empty dict. Every other line must be a key-value assignment containing an equals sign: the key is the text before the FIRST equals sign and the value is everything after it, each stripped of surrounding spaces and tabs; the value may be empty and may contain further equals signs. The key must be non-empty and made only of ASCII letters, ASCII digits, and underscores; a line with no equals sign, or a bad key, -> ValueError('bad line'). A well-formed assignment that appears before any section header -> ValueError('no section'). A key repeated inside the same section -> ValueError('duplicate key'); the same key in different sections is allowed. The empty document returns the empty dict. Output ONLY the function definition.",
        'solution.py',
        'def parse_ini(text):\n    if not isinstance(text, str):\n        raise ValueError("bad input")\n    result = {}\n    current = None\n    for raw in text.split("\\n"):\n        line = raw.strip(" \\t")\n        if line == "" or line[0] in ";#":\n            continue\n        if line[0] == "[":\n            if not line.endswith("]"):\n                raise ValueError("bad section")\n            name = line[1:-1]\n            if name == "" or not all(\n                    "a" <= c <= "z" or "A" <= c <= "Z"\n                    or "0" <= c <= "9" or c == "_" for c in name):\n                raise ValueError("bad section")\n            if name in result:\n                raise ValueError("duplicate section")\n            result[name] = {}\n            current = name\n            continue\n        if "=" not in line:\n            raise ValueError("bad line")\n        key, _, val = line.partition("=")\n        key = key.strip(" \\t")\n        val = val.strip(" \\t")\n        if key == "" or not all(\n                "a" <= c <= "z" or "A" <= c <= "Z"\n                or "0" <= c <= "9" or c == "_" for c in key):\n            raise ValueError("bad line")\n        if current is None:\n            raise ValueError("no section")\n        if key in result[current]:\n            raise ValueError("duplicate key")\n        result[current][key] = val\n    return result\n',
        "import pytest\nfrom solution import parse_ini as f\ndef test_basic():\n    assert f('[db]\\nhost=local\\nport=5432') == {'db': {'host': 'local', 'port': '5432'}}\ndef test_two_sections():\n    assert f('[a]\\nx=1\\n[b]\\nx=2') == {'a': {'x': '1'}, 'b': {'x': '2'}}\ndef test_comments_blank():\n    assert f('; c\\n\\n[s]\\n# c\\nk=v\\n') == {'s': {'k': 'v'}}\ndef test_whitespace():\n    assert f('  [s]  \\n  k  =  v  ') == {'s': {'k': 'v'}}\ndef test_value_with_equals():\n    assert f('[s]\\nk=a=b') == {'s': {'k': 'a=b'}}\ndef test_empty_value():\n    assert f('[s]\\nk=') == {'s': {'k': ''}}\ndef test_empty_section_body():\n    assert f('[s]') == {'s': {}}\ndef test_empty_text():\n    assert f('') == {}\ndef test_same_key_other_section():\n    assert f('[a]\\nk=1\\n[b]\\nk=2') == {'a': {'k': '1'}, 'b': {'k': '2'}}\ndef test_no_section():\n    with pytest.raises(ValueError) as e: f('k=v')\n    assert str(e.value) == 'no section'\ndef test_duplicate_key():\n    with pytest.raises(ValueError) as e: f('[s]\\nk=1\\nk=2')\n    assert str(e.value) == 'duplicate key'\ndef test_duplicate_section():\n    with pytest.raises(ValueError) as e: f('[s]\\nk=1\\n[s]\\nj=2')\n    assert str(e.value) == 'duplicate section'\ndef test_bad_section_unclosed():\n    with pytest.raises(ValueError) as e: f('[s')\n    assert str(e.value) == 'bad section'\ndef test_bad_section_empty():\n    with pytest.raises(ValueError): f('[]')\ndef test_bad_line_no_equals():\n    with pytest.raises(ValueError) as e: f('[s]\\nnovalue')\n    assert str(e.value) == 'bad line'\ndef test_bad_key_char():\n    with pytest.raises(ValueError): f('[s]\\na b=1')\ndef test_bad_input():\n    with pytest.raises(ValueError) as e: f(5)\n    assert str(e.value) == 'bad input'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'lcs_diff_ops',
        "Write a Python function diff_ops(a, b) that computes a line diff between two lists of strings and returns a list of (tag, items) tuples, where tag is one of the strings 'equal', 'delete', 'insert' and items is a list of consecutive elements sharing that tag. a and b must both be lists and every element of both must be a str; otherwise -> ValueError('bad input'). The diff must be MINIMAL: it deletes elements of a and inserts elements of b around an unchanged longest common subsequence, so the total number of deleted plus inserted elements is as small as possible. Among all minimal diffs, produce exactly this one: walk both lists from the front; when the current element of a equals the current element of b, pair them as an 'equal' and advance both; when they differ, emit the current element of a as a 'delete' whenever doing so still permits a minimal diff for the remainders, and only otherwise emit the current element of b as an 'insert'; when one list is exhausted the remainder of the other is all deletes or all inserts. This rule places a delete before an insert whenever both choices would preserve minimality. Consecutive operations with the same tag are coalesced into a single tuple whose items list holds those elements in order. Two empty lists produce the empty list. Output ONLY the function definition.",
        'solution.py',
        'def diff_ops(a, b):\n    if not isinstance(a, list) or not isinstance(b, list):\n        raise ValueError("bad input")\n    for lst in (a, b):\n        for x in lst:\n            if not isinstance(x, str):\n                raise ValueError("bad input")\n    n, m = len(a), len(b)\n    L = [[0] * (m + 1) for _ in range(n + 1)]\n    for i in range(n - 1, -1, -1):\n        for j in range(m - 1, -1, -1):\n            if a[i] == b[j]:\n                L[i][j] = L[i + 1][j + 1] + 1\n            else:\n                L[i][j] = max(L[i + 1][j], L[i][j + 1])\n    ops = []\n    i = j = 0\n    while i < n or j < m:\n        if i < n and j < m and a[i] == b[j]:\n            tag, item = "equal", a[i]\n            i += 1\n            j += 1\n        elif j >= m or (i < n and L[i + 1][j] >= L[i][j + 1]):\n            tag, item = "delete", a[i]\n            i += 1\n        else:\n            tag, item = "insert", b[j]\n            j += 1\n        if ops and ops[-1][0] == tag:\n            ops[-1][1].append(item)\n        else:\n            ops.append((tag, [item]))\n    return ops\n',
        "import pytest\nfrom solution import diff_ops as f\ndef test_replace_middle():\n    assert f(['a', 'b', 'c'], ['a', 'x', 'c']) == [('equal', ['a']), ('delete', ['b']), ('insert', ['x']), ('equal', ['c'])]\ndef test_all_equal(): assert f(['a', 'b'], ['a', 'b']) == [('equal', ['a', 'b'])]\ndef test_both_empty(): assert f([], []) == []\ndef test_insert_only(): assert f([], ['a', 'b']) == [('insert', ['a', 'b'])]\ndef test_delete_only(): assert f(['a', 'b'], []) == [('delete', ['a', 'b'])]\ndef test_disjoint():\n    assert f(['a', 'b'], ['c', 'd']) == [('delete', ['a', 'b']), ('insert', ['c', 'd'])]\ndef test_shift():\n    assert f(['x', 'a'], ['a', 'y']) == [('delete', ['x']), ('equal', ['a']), ('insert', ['y'])]\ndef test_tie_prefers_delete():\n    assert f(['a', 'b', 'a'], ['b', 'a', 'b']) == [('delete', ['a']), ('equal', ['b', 'a']), ('insert', ['b'])]\ndef test_append(): assert f(['a'], ['a', 'b']) == [('equal', ['a']), ('insert', ['b'])]\ndef test_prepend(): assert f(['b'], ['a', 'b']) == [('insert', ['a']), ('equal', ['b'])]\ndef test_bad_input_not_list():\n    with pytest.raises(ValueError) as e: f('ab', [])\n    assert str(e.value) == 'bad input'\ndef test_bad_element():\n    with pytest.raises(ValueError) as e: f([1], [])\n    assert str(e.value) == 'bad input'\n",
        'hard', max_new_tokens=768),
    TaskSpec(
        'fletcher16_checksum',
        "Write a Python function fletcher16(data) that computes the Fletcher-16 checksum and returns it as an int. data may be a str or a list; anything else -> ValueError('bad input'). When data is a str, every character must have a code point of at most 127 (7-bit ASCII); a character beyond that -> ValueError('bad char'); the byte sequence is the characters' code points in order. When data is a list, every element must be an int, must not be a bool, and must lie in the range 0 to 255 inclusive; any other element -> ValueError('bad byte'). The checksum uses two running sums that both start at 0: for each byte in order, first add the byte to the first sum modulo 255, then add the (updated) first sum to the second sum modulo 255. The result is the second sum times 256 plus the first sum. Empty input (empty string or empty list) gives 0. For example, the string 'abcde' gives 51440. Output ONLY the function definition.",
        'solution.py',
        'def fletcher16(data):\n    if isinstance(data, str):\n        byts = []\n        for ch in data:\n            if ord(ch) > 127:\n                raise ValueError("bad char")\n            byts.append(ord(ch))\n    elif isinstance(data, list):\n        for x in data:\n            if not isinstance(x, int) or isinstance(x, bool) or x < 0 or x > 255:\n                raise ValueError("bad byte")\n        byts = data\n    else:\n        raise ValueError("bad input")\n    s1 = s2 = 0\n    for byte in byts:\n        s1 = (s1 + byte) % 255\n        s2 = (s2 + s1) % 255\n    return s2 * 256 + s1\n',
        "import pytest\nfrom solution import fletcher16 as f\ndef test_abcde(): assert f('abcde') == 51440\ndef test_abcdef(): assert f('abcdef') == 8279\ndef test_empty_str(): assert f('') == 0\ndef test_empty_list(): assert f([]) == 0\ndef test_single(): assert f([1]) == 257\ndef test_two(): assert f([1, 2]) == 1027\ndef test_byte_255(): assert f([255]) == 0\ndef test_two_255(): assert f([255, 255]) == 0\ndef test_str_list_agree(): assert f('abcde') == f([97, 98, 99, 100, 101])\ndef test_bad_char():\n    with pytest.raises(ValueError) as e: f('caf\\xe9')\n    assert str(e.value) == 'bad char'\ndef test_bad_byte_range():\n    with pytest.raises(ValueError) as e: f([256])\n    assert str(e.value) == 'bad byte'\ndef test_bad_byte_negative():\n    with pytest.raises(ValueError): f([-1])\ndef test_bad_byte_bool():\n    with pytest.raises(ValueError): f([True])\ndef test_bad_input():\n    with pytest.raises(ValueError) as e: f(5)\n    assert str(e.value) == 'bad input'\n",
        'hard', max_new_tokens=512),
    TaskSpec(
        'md_outline_number',
        "Write a Python function outline_number(lines) that numbers markdown-style headers hierarchically. lines must be a list and every element must be a str; otherwise -> ValueError('bad input'). A line is a header candidate exactly when its FIRST character is a hash. A valid header is 1 to 6 hashes, then exactly one space, then a non-empty title whose first character is not a space; a header candidate that breaks any of those rules (7 or more hashes, no space right after the hashes, an empty title, or a title starting with a space) -> ValueError('bad header'). The title itself may contain further hashes and spaces. The header's level is its number of leading hashes. Lines that do not start with a hash are ignored. The first header must be level 1, and every header may be at most one level deeper than the header before it (any number of levels shallower is fine); a violation -> ValueError('bad nesting'). Number the headers with one counter per level: a header of level k increments the level-k counter and resets all deeper counters, and its output string is the counters for levels 1 through k joined with single dots, then a single space, then the title. So the first level-1 header is '1 Title', its first level-2 child is '1.1 Sub', and a later second level-1 header is '2 Next'. Return the list of these numbered strings in order; a list with no headers returns the empty list. Output ONLY the function definition.",
        'solution.py',
        'def outline_number(lines):\n    if not isinstance(lines, list):\n        raise ValueError("bad input")\n    for ln in lines:\n        if not isinstance(ln, str):\n            raise ValueError("bad input")\n    counters = [0] * 6\n    prev_level = 0\n    out = []\n    for ln in lines:\n        if not ln.startswith("#"):\n            continue\n        i = 0\n        while i < len(ln) and ln[i] == "#":\n            i += 1\n        if i > 6 or i >= len(ln) or ln[i] != " ":\n            raise ValueError("bad header")\n        title = ln[i + 1:]\n        if title == "" or title[0] == " ":\n            raise ValueError("bad header")\n        level = i\n        if level > prev_level + 1:\n            raise ValueError("bad nesting")\n        counters[level - 1] += 1\n        for d in range(level, 6):\n            counters[d] = 0\n        out.append(".".join(str(counters[k]) for k in range(level)) + " " + title)\n        prev_level = level\n    return out\n',
        "import pytest\nfrom solution import outline_number as f\ndef test_basic():\n    assert f(['# A', '## B', '## C', '# D']) == ['1 A', '1.1 B', '1.2 C', '2 D']\ndef test_deep_reset():\n    assert f(['# A', '## B', '### C', '## D', '### E']) == ['1 A', '1.1 B', '1.1.1 C', '1.2 D', '1.2.1 E']\ndef test_ignore_nonheaders():\n    assert f(['text', '# A', 'more', '## B']) == ['1 A', '1.1 B']\ndef test_empty(): assert f([]) == []\ndef test_no_headers(): assert f(['just', 'text']) == []\ndef test_jump_shallow():\n    assert f(['# A', '## B', '### C', '# D']) == ['1 A', '1.1 B', '1.1.1 C', '2 D']\ndef test_title_with_hash(): assert f(['# A # B']) == ['1 A # B']\ndef test_first_not_level1():\n    with pytest.raises(ValueError) as e: f(['## A'])\n    assert str(e.value) == 'bad nesting'\ndef test_skip_level():\n    with pytest.raises(ValueError) as e: f(['# A', '### C'])\n    assert str(e.value) == 'bad nesting'\ndef test_seven_hashes():\n    with pytest.raises(ValueError) as e: f(['####### X'])\n    assert str(e.value) == 'bad header'\ndef test_no_space():\n    with pytest.raises(ValueError): f(['#title'])\ndef test_empty_title():\n    with pytest.raises(ValueError): f(['# '])\ndef test_double_space():\n    with pytest.raises(ValueError): f(['#  x'])\ndef test_bad_input():\n    with pytest.raises(ValueError) as e: f('# A')\n    assert str(e.value) == 'bad input'\ndef test_bad_element():\n    with pytest.raises(ValueError): f([1])\n",
        'hard', max_new_tokens=768),
]


def main() -> int:
    out = seed_batch(BATCH, REGISTRY_PATH)
    for tid, bad in out["rejected"].items():
        print(f"REJECTED {tid}: {json.dumps(bad)}")
    print(f"admitted {len(out['admitted'])}/{len(BATCH)} "
          f"(registry total: {out['registry_total']}; lane target: 100)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
