import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData15 = <String, List<RowanActionClip>>{
  "resume.back_on_run": [
    RowanActionClip(
      eventId: "resume.back_on_run",
      clipId: "cartesia-rowan-situational-pack/v1:resume.back_on_run",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-back-on-run.wav",
      caption: "I'm back on the run.",
      category: "resume",
      context: "resume",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "95d85de1096ef90a72cecf28f1dc0454a1016476dae8fb129b9c18652183baa4",
      audioSha256: "354ff4f5c0427aa815bbe7909b5a452ab0ebc7b3982cd8f351e3fbc3fbdb88ec",
      durationSeconds: 1.04,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "resume.last_saved_state": [
    RowanActionClip(
      eventId: "resume.last_saved_state",
      clipId: "cartesia-rowan-situational-pack/v1:resume.last_saved_state",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-last-saved-state.wav",
      caption: "I'll pick this up from the last saved state.",
      category: "resume",
      context: "resume",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "722ee5476528e61acb1ffe5e10869bd80fa355fae4b1a1fa093acff36dfb5ef5",
      audioSha256: "30c34148a25d5164fac757f27a4da63567e21d2cad48917be0c1beb6424c6cbb",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 4,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "latency.moment": [
    RowanActionClip(
      eventId: "latency.moment",
      clipId: "cartesia-rowan-situational-pack/v1:latency.moment",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-moment.wav",
      caption: "This may take a moment.",
      category: "latency",
      context: "latency",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "94467cb0b06cd7c14c4f673964cccc19afb70ba1de8767af370e96928481bcd9",
      audioSha256: "08a8afb52414cd4584966fcac58ac6c91fae8edc509dcdf96f5d95d5ec8472cd",
      durationSeconds: 1.36,
      recommendedCooldownSeconds: 8,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "latency.waiting_response": [
    RowanActionClip(
      eventId: "latency.waiting_response",
      clipId: "cartesia-rowan-situational-pack/v1:latency.waiting_response",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-waiting-response.wav",
      caption: "I'm still waiting on the response.",
      category: "latency",
      context: "latency",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "8736cdca4b977e50c138391d7d51f37ebcb216c97e4349425bfcae43efe68220",
      audioSha256: "62fd861362d2578a4704fdbca81da2962a4ec6b352b5e2dcf4fa5fbbbfe7dca5",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 10,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "latency.slower_service": [
    RowanActionClip(
      eventId: "latency.slower_service",
      clipId: "cartesia-rowan-situational-pack/v1:latency.slower_service",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-slower-service.wav",
      caption: "The service is taking longer than expected.",
      category: "latency",
      context: "latency",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "b28c67c246480796ca92c86267dd69e744fc06770475bb38c66673d251ac86b3",
      audioSha256: "3321ff6fbe3958ca965f38402e1e8d75608d5f52cbc1be06c602af624adbb5e0",
      durationSeconds: 2.8,
      recommendedCooldownSeconds: 15,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "error.recoverable_path": [
    RowanActionClip(
      eventId: "error.recoverable_path",
      clipId: "cartesia-rowan-situational-pack/v1:error.recoverable_path",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-recoverable-path.wav",
      caption: "That did not work as expected. I'll try the recoverable path.",
      category: "error",
      context: "error",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "ad41dd0cc9fc5afcde4335df58bfa279c97e933d705c84a58cd834bcecdc2454",
      audioSha256: "26edd36638877fddd87499048be27fa27939e3d82cdf345fdba1a5ff571ccd0c",
      durationSeconds: 3.52,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "error.no_result_returned": [
    RowanActionClip(
      eventId: "error.no_result_returned",
      clipId: "cartesia-rowan-situational-pack/v1:error.no_result_returned",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-no-result-returned.wav",
      caption: "The request failed before any result was returned.",
      category: "error",
      context: "error",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "30b308d514dc49b32da5de3dc76bdffb622bb40be653075125d40d168b6e3270",
      audioSha256: "57d855b0df0eef7a7df88a6988ea0c5c640bf06629209d6073ae171026d52652",
      durationSeconds: 3.12,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "evidence.reproduction_failed": [
    RowanActionClip(
      eventId: "evidence.reproduction_failed",
      clipId: "cartesia-rowan-situational-pack/v1:evidence.reproduction_failed",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-reproduction-failed.wav",
      caption: "The result did not reproduce. Let's look at what changed.",
      category: "evidence",
      context: "evidence",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "127cf2f99d837358310f033e3a29b46f4af4f1c760b7916ab950ceed0331e95d",
      audioSha256: "f98f34a6abd6512e19e84e5a9e5c6a7d45f4f638a7241b4927360dcb5e0f3aa8",
      durationSeconds: 3.52,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "evidence.claim_mismatch": [
    RowanActionClip(
      eventId: "evidence.claim_mismatch",
      clipId: "cartesia-rowan-situational-pack/v1:evidence.claim_mismatch",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-claim-mismatch.wav",
      caption: "The evidence does not match the claim yet.",
      category: "evidence",
      context: "evidence",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "7b4f569b28b408b351a650e11253a3b3ab038aa9148581030286ddb491dd9912",
      audioSha256: "7eccdd457a3dfee3ec98524650c99411fe880df2adc2400e7848608b782b61f0",
      durationSeconds: 2.72,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "evidence.cannot_verify": [
    RowanActionClip(
      eventId: "evidence.cannot_verify",
      clipId: "cartesia-rowan-situational-pack/v1:evidence.cannot_verify",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-cannot-verify.wav",
      caption: "I can't verify that from the available evidence.",
      category: "evidence",
      context: "evidence",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "0596b673bcec730b7ce9f286ac384ff0e921aa8aa550d9e1f1a2eaedd9aa5ca4",
      audioSha256: "6df7e5851569758747338882f4fe803699f850c0f5a66e794e92b20ddf7abdcf",
      durationSeconds: 3.04,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "check.named_pass": [
    RowanActionClip(
      eventId: "check.named_pass",
      clipId: "cartesia-rowan-situational-pack/v1:check.named_pass",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-named-check-passed.wav",
      caption: "The check passed for the named criteria.",
      category: "check",
      context: "check",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "dd77669b8622fb156eefcd8e10337034bb7b63ec499cc10b5ab535e2c0868e9c",
      audioSha256: "f93316a3039c78e5036b79b69ed3780d40b56bdd05187c0abf896f46ff9c5e86",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "check.mismatch_found": [
    RowanActionClip(
      eventId: "check.mismatch_found",
      clipId: "cartesia-rowan-situational-pack/v1:check.mismatch_found",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-mismatch-found.wav",
      caption: "The check found a mismatch. You can review the details.",
      category: "check",
      context: "check",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "140dc0cedd09b9914597572d358415e976dee8abba7e74dc9232765026c08f32",
      audioSha256: "fce8eb204d1d9fb7992b357118da1f2e7fd1bc680d832c82bd130f8a1cff9cfa",
      durationSeconds: 3.28,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
};
