import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData8 = <String, List<RowanActionClip>>{
  "verify.receipt_prepare": [
    RowanActionClip(
      eventId: "verify.receipt_prepare",
      clipId: "cartesia-rowan-complete-pack/v1:verify.receipt_prepare",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-receipt-prepare.wav",
      caption: "I'll prepare a receipt for this step.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use before creating a receipt or evidence note.",
      trigger: "Use before creating a receipt or evidence note.",
      textSha256: "6a7596d71c90020dcb79bd980eb62c12b379fb8bc944e18d1f15d6f54dc45fe3",
      audioSha256: "0deb41b7567834dbf888177ac79dcfecf7ab69470fb6757ed84cc4e7e35d53b9",
      durationSeconds: 2.08,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/verify-receipt-prepare.json",
    ),
  ],
  "verify.receipt_linked": [
    RowanActionClip(
      eventId: "verify.receipt_linked",
      clipId: "cartesia-rowan-complete-pack/v1:verify.receipt_linked",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-receipt-linked.wav",
      caption: "The receipt is linked to this event.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use only after an event receipt has been linked.",
      trigger: "Use only after an event receipt has been linked.",
      textSha256: "6f1ff0d23f2f1af42bae11f66bfafe8764f6abca2498cff784e045712d16ec28",
      audioSha256: "a5ba1aa18504fbac10690eaa5a48ad5a202652e391c67f2f1ea6c36ca1604d63",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/verify-receipt-linked.json",
    ),
  ],
  "verify.observed_only": [
    RowanActionClip(
      eventId: "verify.observed_only",
      clipId: "cartesia-rowan-complete-pack/v1:verify.observed_only",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-observed-only.wav",
      caption: "That is an observation, not a conclusion yet.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use when separating observed facts from conclusions.",
      trigger: "Use when separating observed facts from conclusions.",
      textSha256: "a7a5ac707960a650eed0cc0e89d678610a91080adfbd1e9477f0d400f07d07be",
      audioSha256: "50f5f55890701ebeedb5623bf9b636fb64ddcbb315c964650dae23bd27731263",
      durationSeconds: 3.04,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-observed-only.json",
    ),
  ],
  "verify.inferred_label": [
    RowanActionClip(
      eventId: "verify.inferred_label",
      clipId: "cartesia-rowan-complete-pack/v1:verify.inferred_label",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-inferred-label.wav",
      caption: "I'll mark that as inferred.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use when a claim is inferred rather than directly observed.",
      trigger: "Use when a claim is inferred rather than directly observed.",
      textSha256: "52ab9f7db81782a421e4ae52c7e7bce3385ab14b0aa6e6e073a3592b5908d711",
      audioSha256: "ec390f279eded2cca00994df6daf703fc35bd3340e375606616635c0f05a879e",
      durationSeconds: 1.6,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-inferred-label.json",
    ),
  ],
  "verify.unknown_label": [
    RowanActionClip(
      eventId: "verify.unknown_label",
      clipId: "cartesia-rowan-complete-pack/v1:verify.unknown_label",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-unknown-label.wav",
      caption: "I'll mark that as unknown.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use when evidence is missing or unavailable.",
      trigger: "Use when evidence is missing or unavailable.",
      textSha256: "d2a5330ed639393015e62082157ccd6c8f7a438cbc20eff153ca227b3f83ac75",
      audioSha256: "8ce294f5db034785011bcd74b5848bc7c2d1d1960c539b25229180b104a0aa87",
      durationSeconds: 1.84,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-unknown-label.json",
    ),
  ],
  "verify.does_not_prove": [
    RowanActionClip(
      eventId: "verify.does_not_prove",
      clipId: "cartesia-rowan-complete-pack/v1:verify.does_not_prove",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-does-not-prove.wav",
      caption: "This check does not prove the broader claim.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use when a passing check has a limited scope.",
      trigger: "Use when a passing check has a limited scope.",
      textSha256: "9f561f0038b40df578698f45be6bcc9902f82e8d1649a789482d1af473e2d98b",
      audioSha256: "70ce4ffcd72396e21aaf555818918093d935f8f10fe637c0b857df5a6a6ec5e3",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-does-not-prove.json",
    ),
  ],
  "verify.negative_control": [
    RowanActionClip(
      eventId: "verify.negative_control",
      clipId: "cartesia-rowan-complete-pack/v1:verify.negative_control",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-negative-control.wav",
      caption: "I'll include a negative control if we test this.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use when designing a validation or benchmark with a false-success check.",
      trigger: "Use when designing a validation or benchmark with a false-success check.",
      textSha256: "ae51bd551b2156da17b90267fea8e7111e08ff7b4d266fd57744eb29cf91d8f2",
      audioSha256: "e4ae5abf025f1ac3b93ea85eb60d647f1c68228fb5d8e0cb4b65b03d8be6158a",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-negative-control.json",
    ),
  ],
  "verify.current_source": [
    RowanActionClip(
      eventId: "verify.current_source",
      clipId: "cartesia-rowan-complete-pack/v1:verify.current_source",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-current-source.wav",
      caption: "I'll refresh the source before using it.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use before relying on external or drift-prone information.",
      trigger: "Use before relying on external or drift-prone information.",
      textSha256: "343ad2f92c4b88c3cd03c1acc38110a0f3a7131b6f1263aa5955825c3b74d269",
      audioSha256: "da8042061f36d59a1213ef7aa772b767c1f1b1ee569beb15ff3e84cea843c0fc",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-current-source.json",
    ),
  ],
  "recovery.retry": [
    RowanActionClip(
      eventId: "recovery.retry",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.retry",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-retry.wav",
      caption: "I'll retry with the safer path.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use after a recoverable failure before retrying.",
      trigger: "Use after a recoverable failure before retrying.",
      textSha256: "c61cc5530cc1b462090d86041383ab49fb58369c59e8743ff59ceb4d2b9b8915",
      audioSha256: "c1c293b27b684dce1a578202a69845504e14697f381ac0679c738c1f308893f2",
      durationSeconds: 2,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-retry.json",
    ),
  ],
  "recovery.backoff": [
    RowanActionClip(
      eventId: "recovery.backoff",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.backoff",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-backoff.wav",
      caption: "I'll wait before trying that again.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use before backing off after rate limit or transient failure.",
      trigger: "Use before backing off after rate limit or transient failure.",
      textSha256: "bda1c48ab7ec49301aedc45099042ee93c80bb5b12c227432cbae11c43ed31a2",
      audioSha256: "d4128c63dabf740f20fb78e9395dfa36f670057897b658751b63bd0d2286ac69",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-backoff.json",
    ),
  ],
  "recovery.partial_result": [
    RowanActionClip(
      eventId: "recovery.partial_result",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.partial_result",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-partial-result.wav",
      caption: "There is a partial result to inspect.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only when a partial output exists.",
      trigger: "Use only when a partial output exists.",
      textSha256: "8a33ceba7af160c7c1f06e167f4ccad7ca348abe7876938132c105098b7b7aeb",
      audioSha256: "62a9de8133b0016cbeb2bda0415f6bc3c9e2f832a04b0ac1fffbbfe33e4df7da",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-partial-result.json",
    ),
  ],
  "recovery.state_saved": [
    RowanActionClip(
      eventId: "recovery.state_saved",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.state_saved",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-state-saved.wav",
      caption: "The current state is preserved.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after state has been saved or snapshotted.",
      trigger: "Use only after state has been saved or snapshotted.",
      textSha256: "62f0bfe6db342da317db36ef9a5d0d6b37f4e62d14d7d548acc477fb906f5503",
      audioSha256: "6c279c36c7f3f943c2455670295c69d1c1d28e9a2daba56b2f5be6a06b3ca1fc",
      durationSeconds: 2,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/recovery-state-saved.json",
    ),
  ],
};
