import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData1 = <String, List<RowanActionClip>>{
  "onboarding.welcome": [
    RowanActionClip(
      eventId: "onboarding.welcome",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.welcome",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/welcome.wav",
      caption: "Hi, I'm Rowan. What would you like to work on?",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when Rowan is introduced at the start of a session.",
      trigger: "Use when Rowan is introduced at the start of a session.",
      textSha256: "57dd75d5355366ac66576199a052e87fd52da820ab99832391e6ac2ba78555b4",
      audioSha256: "9eadbb13209b079fb82e994ec99cc8425557748237c910714425fe6e92f97cf3",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/welcome.json",
    ),
  ],
  "onboarding.open_task": [
    RowanActionClip(
      eventId: "onboarding.open_task",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.open_task",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-open-task.wav",
      caption: "We can start with a task, a question, or a file.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when the user enters Rowan without a specific task yet.",
      trigger: "Use when the user enters Rowan without a specific task yet.",
      textSha256: "d9cac409e7e4037bb8eb0068f50bafe756ca75a5c8347e493de645699ef57a7c",
      audioSha256: "1080e9003eea381fcf4bedf55d8c94e97176a07d7b914173fe7e040af50b8194",
      durationSeconds: 4,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/onboarding-open-task.json",
    ),
  ],
  "onboarding.choose_mode": [
    RowanActionClip(
      eventId: "onboarding.choose_mode",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.choose_mode",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-choose-mode.wav",
      caption: "Tell me the outcome you want, and I'll shape the run.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when prompting for the desired outcome before planning.",
      trigger: "Use when prompting for the desired outcome before planning.",
      textSha256: "8cad9e50040434e3d9ccfdf69ac07a182877f2dfaa9b0791d498035969c2df74",
      audioSha256: "ffeadc13746322fed9c5e3c661d45a0099494996e90f0c23f607d31f22813d2a",
      durationSeconds: 2.8,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/onboarding-choose-mode.json",
    ),
  ],
  "onboarding.first_prompt": [
    RowanActionClip(
      eventId: "onboarding.first_prompt",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.first_prompt",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-first-prompt.wav",
      caption: "A rough prompt is enough. I can help tighten it.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when encouraging a first draft prompt or rough request.",
      trigger: "Use when encouraging a first draft prompt or rough request.",
      textSha256: "ce0d0c505ab2ee3c8029aba75be98b2d5cffbe75fce39c855aaf0709a83239d0",
      audioSha256: "16f4a9fe28a7430caa32f9c7b0082b9434ed9b3f1fb51d6c6f891e4bd2092601",
      durationSeconds: 2.72,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/onboarding-first-prompt.json",
    ),
  ],
  "onboarding.workspace_intro": [
    RowanActionClip(
      eventId: "onboarding.workspace_intro",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.workspace_intro",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-workspace-intro.wav",
      caption: "I can work from the current workspace when you ask.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when describing workspace-aware work before any file access.",
      trigger: "Use when describing workspace-aware work before any file access.",
      textSha256: "5e481b9ab0293cf850a2b26eb2c6e0c0a5cab80bf1777272fe32d9db782ab2f1",
      audioSha256: "d9728d2e51d9ba49e6ecb066f34a568b94b1c3d48b04940f33b44c025f80d385",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/onboarding-workspace-intro.json",
    ),
  ],
  "onboarding.public_task": [
    RowanActionClip(
      eventId: "onboarding.public_task",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.public_task",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-public-task.wav",
      caption: "For public work, I'll keep claims tied to evidence.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when the user starts public-facing writing or release work.",
      trigger: "Use when the user starts public-facing writing or release work.",
      textSha256: "7fc05f0f63568c3875e80a24b70604f6f99aa5c3c0733b88be4dbbce7a953efe",
      audioSha256: "55d5206fdb8ea9198aabc6a2a8b29bcbc54efd351d454b330f1b1ed9d2f78fe9",
      durationSeconds: 3.52,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/onboarding-public-task.json",
    ),
  ],
  "onboarding.private_task": [
    RowanActionClip(
      eventId: "onboarding.private_task",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.private_task",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-private-task.wav",
      caption: "We can keep the working record on this device.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when the user marks a task private or local-only.",
      trigger: "Use when the user marks a task private or local-only.",
      textSha256: "a5566926748343b84269b6c11d2d96f8fb60bb3fffce43b5af606e2d6c7d716c",
      audioSha256: "a4cf7051fb9588d284fed46b9704cab68ad85cfead9334a872eb485d4269b1dd",
      durationSeconds: 2.72,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/onboarding-private-task.json",
    ),
  ],
  "onboarding.review_before_action": [
    RowanActionClip(
      eventId: "onboarding.review_before_action",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.review_before_action",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-review-before-action.wav",
      caption: "I'll prepare the change before any final approval step.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use before preparing a reviewable artifact that may later need approval.",
      trigger: "Use before preparing a reviewable artifact that may later need approval.",
      textSha256: "7aa4c7f85ce22345afe3637d7d1559d9ab272e5461cc87fccd3f8953c89fe3dd",
      audioSha256: "9b2f7351e6a58fdedf7b84a16fa8738b0560c8d81e8e27d1ed0805387c2db8c5",
      durationSeconds: 3.36,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/onboarding-review-before-action.json",
    ),
  ],
  "onboarding.user_control": [
    RowanActionClip(
      eventId: "onboarding.user_control",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.user_control",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-user-control.wav",
      caption: "You can steer or stop me at any point.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when introducing user control during an active session.",
      trigger: "Use when introducing user control during an active session.",
      textSha256: "a607f8c29da3afc8ded2301dfda39c6cce80230a838063103aaa775bf1da7341",
      audioSha256: "90a69f06c00a908360d6e706ee33a92f57387b17992cd0e11abe4c8e292fa9f0",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/onboarding-user-control.json",
    ),
  ],
  "onboarding.ready_options": [
    RowanActionClip(
      eventId: "onboarding.ready_options",
      clipId: "cartesia-rowan-complete-pack/v1:onboarding.ready_options",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/onboarding-ready-options.wav",
      caption: "I can help write, build, check, or explain.",
      category: "onboarding",
      context: "onboarding",
      prerequisite: "Use when presenting broad starting options.",
      trigger: "Use when presenting broad starting options.",
      textSha256: "2d3df74aa13734fa77fce3c485be791df0b4b43c92b5514fd0328c6a466be569",
      audioSha256: "43da7772071af247b085e9f498ca8ae086c3bac6facb3b5c39bda276f929f6cd",
      durationSeconds: 3.6,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/onboarding-ready-options.json",
    ),
  ],
  "chat.new_thread": [
    RowanActionClip(
      eventId: "chat.new_thread",
      clipId: "cartesia-rowan-complete-pack/v1:chat.new_thread",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-new-thread.wav",
      caption: "I can open a fresh branch of the conversation.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use when offering a new task or conversation branch.",
      trigger: "Use when offering a new task or conversation branch.",
      textSha256: "86ab3921e0951c62d29db083b172601a9d15b81014bd379569f4133c27674df9",
      audioSha256: "75f16fb942bc729b319b430e29fdc532cc7b50cc28158c6f9cc137b6c4265508",
      durationSeconds: 3.36,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-new-thread.json",
    ),
  ],
  "chat.branch_named": [
    RowanActionClip(
      eventId: "chat.branch_named",
      clipId: "cartesia-rowan-complete-pack/v1:chat.branch_named",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-branch-named.wav",
      caption: "This branch can carry that direction.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use after a branch has been created or selected for a direction.",
      trigger: "Use after a branch has been created or selected for a direction.",
      textSha256: "83c8887baf95dbf26d13f6efe0641aaf8326d9bd620c0e1f036d85d0036fb3b7",
      audioSha256: "4fc0d67c7c62db93d6a1d0fa390e14994f6582af14fdc3d55f38b5196b54e3c7",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-branch-named.json",
    ),
  ],
};
