import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData5 = <String, List<RowanActionClip>>{
  "privacy.microphone_on": [
    RowanActionClip(
      eventId: "privacy.microphone_on",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.microphone_on",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-microphone-on.wav",
      caption: "Voice input is ready.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use only after microphone or voice input is enabled.",
      trigger: "Use only after microphone or voice input is enabled.",
      textSha256: "60ce6f7742ef361cecb824b7925749c9157494f20045f2d17a5f0666680ff955",
      audioSha256: "ca6b188560557153dd40dcc8a7c74b4c27431113f7de1ebdb7f4f2a820f180a4",
      durationSeconds: 1.52,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/privacy-microphone-on.json",
    ),
  ],
  "privacy.local_only": [
    RowanActionClip(
      eventId: "privacy.local_only",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.local_only",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-local-only.wav",
      caption: "I'll keep this step local.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use when a task is explicitly local-only or private-local.",
      trigger: "Use when a task is explicitly local-only or private-local.",
      textSha256: "f3a90973bfe820d34c618f0e5fddbef19f59cf848a0b93d15fb78d4367a02cc8",
      audioSha256: "d2bacb19d8b090849c263fcf02768de977c74b6be3d10103709e5d3bfb785383",
      durationSeconds: 1.52,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-local-only.json",
    ),
  ],
  "privacy.external_before_send": [
    RowanActionClip(
      eventId: "privacy.external_before_send",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.external_before_send",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-external-before-send.wav",
      caption: "You can review the outgoing text before sending.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use before drafting outbound text that may later be sent.",
      trigger: "Use before drafting outbound text that may later be sent.",
      textSha256: "6bb0f2cab5deced4124ddf8318c69ab8c8cf414722816968744111b11f7b5562",
      audioSha256: "2d5b34df8b4f71344cae07f6e6550e0c68c6109b2f723f68758ebcc8b30bb4d2",
      durationSeconds: 2.96,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-external-before-send.json",
    ),
  ],
  "privacy.secret_boundary": [
    RowanActionClip(
      eventId: "privacy.secret_boundary",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.secret_boundary",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-secret-boundary.wav",
      caption: "Let's keep secrets out of this conversation.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use when secret handling or redaction boundaries matter.",
      trigger: "Use when secret handling or redaction boundaries matter.",
      textSha256: "8edd0718f5900851744891ff5d09d0861fa0829a8770bda2e32ec243cddddccf",
      audioSha256: "20de3b106dca16a5cbdd103a94caeefea62f06af01d2d8846b3730c590e536a8",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-secret-boundary.json",
    ),
  ],
  "privacy.redaction_ready": [
    RowanActionClip(
      eventId: "privacy.redaction_ready",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.redaction_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-redaction-ready.wav",
      caption: "I can redact private details before export.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use when offering redaction before producing an export.",
      trigger: "Use when offering redaction before producing an export.",
      textSha256: "f917ea5e425f8e7997a18482a75bd7b33caeed41c65040f6f470d423999a3ea9",
      audioSha256: "4e1abd538e4a8df34addcdd5a44edc79a9e55626b112728531face58b4d058ba",
      durationSeconds: 2.96,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-redaction-ready.json",
    ),
  ],
  "privacy.replay_disclosure": [
    RowanActionClip(
      eventId: "privacy.replay_disclosure",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.replay_disclosure",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-replay-disclosure.wav",
      caption: "Recorded playback should be labeled before it is shown.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use before replaying a saved clip or demo timeline.",
      trigger: "Use before replaying a saved clip or demo timeline.",
      textSha256: "c14ecfac4872336bd59ac9426f4ccf67d29f49018255711997e54af493ca21f8",
      audioSha256: "c56d0cc44ab1e8b4877157d7fc2a242a9421fe16c9af452343fb454ccae6ae67",
      durationSeconds: 3.44,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-replay-disclosure.json",
    ),
  ],
  "studio.open": [
    RowanActionClip(
      eventId: "studio.open",
      clipId: "cartesia-rowan-complete-pack/v1:studio.open",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-open.wav",
      caption: "I'll open Studio for this pass.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use when opening or switching into Studio mode.",
      trigger: "Use when opening or switching into Studio mode.",
      textSha256: "028b379f05abcb51d950fe56269b9302abcdea5aac60927092d012fb861dea17",
      audioSha256: "e1354520aafc46bd1c51ce08c4e2f2e9f34bfa5b7326c9c70bd06bfebc9773a9",
      durationSeconds: 2,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-open.json",
    ),
  ],
  "studio.scene_select": [
    RowanActionClip(
      eventId: "studio.scene_select",
      clipId: "cartesia-rowan-complete-pack/v1:studio.scene_select",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-scene-select.wav",
      caption: "I'll use this scene as the working cut.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use after a scene is selected for editing.",
      trigger: "Use after a scene is selected for editing.",
      textSha256: "a1a718ff4fec12e693ca127e615a0962de7406881b9cd28d461111b26876ff46",
      audioSha256: "900f65f26a9590d708da695a7717da54a558ee7e82fcf8d3a012e819e5c518b7",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-scene-select.json",
    ),
  ],
  "studio.visual_pass": [
    RowanActionClip(
      eventId: "studio.visual_pass",
      clipId: "cartesia-rowan-complete-pack/v1:studio.visual_pass",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-visual-pass.wav",
      caption: "I'll make a visual pass now.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use when starting visual refinement.",
      trigger: "Use when starting visual refinement.",
      textSha256: "5b80758e87fee9e5a4d4277df7dd6a31e10cb4ec04f938aaf609c07e6f191dca",
      audioSha256: "af87be35736efcda5139a9ec9892f311d79e660f0b7cefaf5af8abb1f922d768",
      durationSeconds: 1.68,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-visual-pass.json",
    ),
  ],
  "studio.audio_pass": [
    RowanActionClip(
      eventId: "studio.audio_pass",
      clipId: "cartesia-rowan-complete-pack/v1:studio.audio_pass",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-audio-pass.wav",
      caption: "I'll make an audio pass now.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use when starting audio refinement.",
      trigger: "Use when starting audio refinement.",
      textSha256: "0b1b43dc8ffed05f636dc290446a27f4327beb4f1701cf25fd819709982b0856",
      audioSha256: "34b74195a0c100c043fca01a834cec5a53797f16315fece58de9cf9784f95eca",
      durationSeconds: 1.52,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-audio-pass.json",
    ),
  ],
  "studio.caption_check": [
    RowanActionClip(
      eventId: "studio.caption_check",
      clipId: "cartesia-rowan-complete-pack/v1:studio.caption_check",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-caption-check.wav",
      caption: "I'll check the captions against the script.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use before caption/script alignment work.",
      trigger: "Use before caption/script alignment work.",
      textSha256: "25a6ca613e42f96e211ee28b9e39a13597b76e09da0ee7701a0d74a30a0cbf6b",
      audioSha256: "32c87228dfe568c66d41a7db3b763e78002413205f8c40a47e38534a387cd972",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-caption-check.json",
    ),
  ],
  "studio.timeline_review": [
    RowanActionClip(
      eventId: "studio.timeline_review",
      clipId: "cartesia-rowan-complete-pack/v1:studio.timeline_review",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-timeline-review.wav",
      caption: "I'll review the timeline for gaps.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use before timeline QA or sequence review.",
      trigger: "Use before timeline QA or sequence review.",
      textSha256: "de4ed0032d2d57dd6ce8e49b5c5704f07935f637971cf6f379bbd074d7ae7dad",
      audioSha256: "48feffe7dc31f198dffb35e579e298e4e840c5563253f2fb27b9dab8d8aec4a5",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-timeline-review.json",
    ),
  ],
};
