import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData11 = <String, List<RowanActionClip>>{
  "export.slides_ready": [
    RowanActionClip(
      eventId: "export.slides_ready",
      clipId: "cartesia-rowan-complete-pack/v1:export.slides_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-slides-ready.wav",
      caption: "The slide deck is ready to review.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use only after the deck exists.",
      trigger: "Use only after the deck exists.",
      textSha256: "825aa67fde252b257f3d46dd8fae3692236e53945c79116028e00feb059a63da",
      audioSha256: "2f5a4b708d64a6b964cb1d43cfc0d54cc26e7232397e2da4b47e48039746bd82",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/export-slides-ready.json",
    ),
  ],
  "export.markdown_ready": [
    RowanActionClip(
      eventId: "export.markdown_ready",
      clipId: "cartesia-rowan-complete-pack/v1:export.markdown_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-markdown-ready.wav",
      caption: "The Markdown export is ready.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use only after the Markdown export exists.",
      trigger: "Use only after the Markdown export exists.",
      textSha256: "2a978a87d8ae8b2aec14492e0d78e9de646b7056d70165852e2d5e0e53ce9063",
      audioSha256: "c395aec2941f812a3a2599b17f0eba53997d6cdae2c28a65bf94aa438d589bbb",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/export-markdown-ready.json",
    ),
  ],
  "export.share_pending": [
    RowanActionClip(
      eventId: "export.share_pending",
      clipId: "cartesia-rowan-complete-pack/v1:export.share_pending",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-share-pending.wav",
      caption: "Sharing is pending your final review.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use before any user-visible share or send step.",
      trigger: "Use before any user-visible share or send step.",
      textSha256: "289bcc36729e6d444e880502272a924a51d007494f53c6f19936be4f814dc697",
      audioSha256: "754c45d95e0e0e6fe59db8f57775e50ea219b4957acd294e9f15015db2ade111",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/export-share-pending.json",
    ),
  ],
  "presentation.open": [
    RowanActionClip(
      eventId: "presentation.open",
      clipId: "cartesia-rowan-complete-pack/v1:presentation.open",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/presentation-open.wav",
      caption: "I'll open the presentation view.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use when switching to a presentation or deck view.",
      trigger: "Use when switching to a presentation or deck view.",
      textSha256: "bf100207d997a48371be50b66283a608443b4a0654f23fd8bfa532caed55f5db",
      audioSha256: "ca5e3dc44de60c98d0c1922c957fd9e256dbb2f4a02bf6b10beff7d334850b38",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/presentation-open.json",
    ),
  ],
  "presentation.speaker_notes": [
    RowanActionClip(
      eventId: "presentation.speaker_notes",
      clipId: "cartesia-rowan-complete-pack/v1:presentation.speaker_notes",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/presentation-speaker-notes.wav",
      caption: "I'll prepare speaker notes from the script.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use before generating speaker notes.",
      trigger: "Use before generating speaker notes.",
      textSha256: "cb83350ba1a4992529c09947fe9196c42bba4e335868385ead51582cd3092685",
      audioSha256: "d145d44408496afb80164b74e33f30b330a676d462b103aa10742d869b4f10ba",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/presentation-speaker-notes.json",
    ),
  ],
  "presentation.citation_check": [
    RowanActionClip(
      eventId: "presentation.citation_check",
      clipId: "cartesia-rowan-complete-pack/v1:presentation.citation_check",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/presentation-citation-check.wav",
      caption: "I'll check citations before the deck leaves.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use before presenting or exporting cited material.",
      trigger: "Use before presenting or exporting cited material.",
      textSha256: "a9c5b1002373903aa35045f4945991e2aa671d1492c3016de1220842e8487821",
      audioSha256: "db664a7fcbefc64e2a8df58e714d36840f9718b409913daacbb3c8a3dd21f6df",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/presentation-citation-check.json",
    ),
  ],
  "reaction.steady_steps": [
    RowanActionClip(
      eventId: "reaction.steady_steps",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.steady_steps",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/steady-steps.wav",
      caption: "All right, let's take it one step at a time.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "359fea6c199e78987d0d7a0186142c0f7e65facaacd1f5731148e29149242f31",
      audioSha256: "737c5fc2f5aac8fc4e894ff3f4e42b118a1af0583c5c61e5c32c53dab185f779",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/steady-steps.json",
    ),
  ],
  "reaction.useful_clue": [
    RowanActionClip(
      eventId: "reaction.useful_clue",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.useful_clue",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/useful-clue.wav",
      caption: "That's a useful clue.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "706becc2f2f2f1d32557d641bf8a682aef0cfe6c071b3df30e2a982f206e39bd",
      audioSha256: "75a28344aa1b2d747e62e119c7ffc9e92d94debd3f8d5a91e5400f48f5b33d99",
      durationSeconds: 1.44,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/useful-clue.json",
    ),
  ],
  "reaction.another_angle": [
    RowanActionClip(
      eventId: "reaction.another_angle",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.another_angle",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/another-angle.wav",
      caption: "Let's try another angle.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "79bce4ac978f7f5858ff4f36638888190c7ccfd788b55859c653d411fad20b52",
      audioSha256: "b0ff2827205eb940a60aab0b038479b025888a8d692485d6a92c60efef98169a",
      durationSeconds: 1.36,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/another-angle.json",
    ),
  ],
  "reaction.check_discrepancy": [
    RowanActionClip(
      eventId: "reaction.check_discrepancy",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.check_discrepancy",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/check-discrepancy.wav",
      caption: "Something doesn't add up. I'll check it.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "c8a5dffdb28e08b304ff933c8d246e7c7c6c29038b4e892e310181e3cb941a6f",
      audioSha256: "3beb19ed27b13b80dc04028102c7c10985d036fda53843b32095fb7475df960b",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/check-discrepancy.json",
    ),
  ],
  "reaction.take_your_time": [
    RowanActionClip(
      eventId: "reaction.take_your_time",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.take_your_time",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/take-your-time.wav",
      caption: "No rush. I'll be here when you're ready.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "24623f7cc057548c38e6d7a4fec6744d01dc56f4d2199a67b8db611d3f1a66c4",
      audioSha256: "fea5de6b7d5f3660001cf3766d8da28f9ca244992a91dac919bfedf9f8022997",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/take-your-time.json",
    ),
  ],
  "reaction.return_later": [
    RowanActionClip(
      eventId: "reaction.return_later",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.return_later",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/return-later.wav",
      caption: "We can pick this up later.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "ef26b0b7c763e94177a04f317a32d8d6cf830b69686a49a65c9ffdc01c4366ab",
      audioSha256: "4b51e15af0734f571cf501cf94ec3f6135e5ec733e3c20a2a99ae42783fd2b25",
      durationSeconds: 1.44,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/return-later.json",
    ),
  ],
};
