import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData2 = <String, List<RowanActionClip>>{
  "chat.branch_return": [
    RowanActionClip(
      eventId: "chat.branch_return",
      clipId: "cartesia-rowan-complete-pack/v1:chat.branch_return",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-branch-return.wav",
      caption: "We can return to the main thread now.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use when offering to navigate back to the main thread.",
      trigger: "Use when offering to navigate back to the main thread.",
      textSha256: "5b63884e04df891a5c1598587c0f2d27f1ec9d847226115afd7fa6b45331f084",
      audioSha256: "7a5485d42790691725d2d4ad6297b749fbfd0b8824eb3321345ae117c85a722e",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-branch-return.json",
    ),
  ],
  "chat.bookmark_offer": [
    RowanActionClip(
      eventId: "chat.bookmark_offer",
      clipId: "cartesia-rowan-complete-pack/v1:chat.bookmark_offer",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-bookmark-offer.wav",
      caption: "I can bookmark this point for later.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use before creating a bookmark or saved point.",
      trigger: "Use before creating a bookmark or saved point.",
      textSha256: "1d31ba3fe6686dbcbbd915406f80265b2197127cdc666d97641e94455b202f95",
      audioSha256: "34f5d3c71b76bfedcd365809ffda596ed91557a84b7ed801a6abd4b04f466651",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-bookmark-offer.json",
    ),
  ],
  "chat.bookmark_added": [
    RowanActionClip(
      eventId: "chat.bookmark_added",
      clipId: "cartesia-rowan-complete-pack/v1:chat.bookmark_added",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-bookmark-added.wav",
      caption: "This point is marked for later review.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use only after a bookmark or marker exists.",
      trigger: "Use only after a bookmark or marker exists.",
      textSha256: "4aca713b6494df25f6b1373f45ea0c99d2d63fcb3abbca3bd8dacb7af731628c",
      audioSha256: "92908087132bb90da20863bf31faf2c3895e49b57c7e1687de75986c6606b4b1",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-bookmark-added.json",
    ),
  ],
  "chat.history_search": [
    RowanActionClip(
      eventId: "chat.history_search",
      clipId: "cartesia-rowan-complete-pack/v1:chat.history_search",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-history-search.wav",
      caption: "I'll search the conversation record for that.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use only when starting a search over available conversation history.",
      trigger: "Use only when starting a search over available conversation history.",
      textSha256: "bdbed97dfabb46fa4e6fbbc1bf3fb749c57b50a9066cea14eda07c424eebb23b",
      audioSha256: "5921f6105f3b7bee33505cf1ed69fa5091f56411058b496fdf87ac1d6ad6fd40",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-history-search.json",
    ),
  ],
  "chat.context_compact": [
    RowanActionClip(
      eventId: "chat.context_compact",
      clipId: "cartesia-rowan-complete-pack/v1:chat.context_compact",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-context-compact.wav",
      caption: "I'll keep the current goal attached to the shorter context.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use when compacting or summarizing context while preserving the active goal.",
      trigger: "Use when compacting or summarizing context while preserving the active goal.",
      textSha256: "78bac9f6f84cdc89eb413316510bbe88670661a93a0507d3d2d22125a88fe12e",
      audioSha256: "99180d934412023795db98bf1d3830720f85c0be327ae971908347e5bed35b66",
      durationSeconds: 3.52,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/chat-context-compact.json",
    ),
  ],
  "chat.topic_shift": [
    RowanActionClip(
      eventId: "chat.topic_shift",
      clipId: "cartesia-rowan-complete-pack/v1:chat.topic_shift",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-topic-shift.wav",
      caption: "I'll carry that forward as the new focus.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use after the user redirects the current task focus.",
      trigger: "Use after the user redirects the current task focus.",
      textSha256: "0bdf18322e886c54337eadacd1dd3cdd47cfa6b04960a3651f50fa95dcfad276",
      audioSha256: "a66f36774e72eff4136bda76e28127dd057d4d23a89c8f7ba37e98c4c3f74913",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-topic-shift.json",
    ),
  ],
  "chat.note_added": [
    RowanActionClip(
      eventId: "chat.note_added",
      clipId: "cartesia-rowan-complete-pack/v1:chat.note_added",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-note-added.wav",
      caption: "That note is added to the working thread.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use only after a note has been written into the working record.",
      trigger: "Use only after a note has been written into the working record.",
      textSha256: "1792458cf3028b38ad6ca18cc066c82e4a7fd6c4cb96c56135edefdd76078e21",
      audioSha256: "549b81ac6d1e8a45936a3bc589169cfef49e50d5c531f7d6a3fb293060d43af7",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-note-added.json",
    ),
  ],
  "chat.jump_to_source": [
    RowanActionClip(
      eventId: "chat.jump_to_source",
      clipId: "cartesia-rowan-complete-pack/v1:chat.jump_to_source",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-jump-to-source.wav",
      caption: "I'll open the source behind that point.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use only when opening a cited source or file reference.",
      trigger: "Use only when opening a cited source or file reference.",
      textSha256: "489ecf3d516b07631b5f517ec70dae4b3644f19367caa2cb15e5e66835f7cbfb",
      audioSha256: "05057ac0bd72b55d01d69235f32e2a93ce36891b8ac8ccbb60947cef3f3a7b56",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-jump-to-source.json",
    ),
  ],
  "chat.compare_threads": [
    RowanActionClip(
      eventId: "chat.compare_threads",
      clipId: "cartesia-rowan-complete-pack/v1:chat.compare_threads",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-compare-threads.wav",
      caption: "I can compare those two branches.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use when offering or preparing a comparison between branches.",
      trigger: "Use when offering or preparing a comparison between branches.",
      textSha256: "86699a5338fcc64c3f9fcbdb0c8df9b6655a1d8ce2f55500921a5eb76fa60ecf",
      audioSha256: "a8a7d3ac092019139f0748f1c7e52ee81484c6773abaeeca382ab276eb0377b4",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/chat-compare-threads.json",
    ),
  ],
  "chat.archive_ready": [
    RowanActionClip(
      eventId: "chat.archive_ready",
      clipId: "cartesia-rowan-complete-pack/v1:chat.archive_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/chat-archive-ready.wav",
      caption: "This task is ready to archive when you are.",
      category: "chat_navigation",
      context: "chat_navigation",
      prerequisite: "Use when work appears complete but archival remains user-controlled.",
      trigger: "Use when work appears complete but archival remains user-controlled.",
      textSha256: "27c86afc521336704adedba20c9e18c954584179508d8f0412aec6fc92ab513a",
      audioSha256: "571936e4f35b3b5d99f40576e79347f7b5d5405b43fe68de46d42c26fd0a0c94",
      durationSeconds: 2.72,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/chat-archive-ready.json",
    ),
  ],
  "model.select_default": [
    RowanActionClip(
      eventId: "model.select_default",
      clipId: "cartesia-rowan-complete-pack/v1:model.select_default",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-select-default.wav",
      caption: "I'll use the default model for this task.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use after choosing the configured default model route.",
      trigger: "Use after choosing the configured default model route.",
      textSha256: "32c1af6c92721f864abfc459ee55d9a5a8ed3ae12f5d860251d43f29807a5bbf",
      audioSha256: "7da34043c4491a59315f9f2c1f3b6ad9c779fa8eb307431c1a1d9874271c9e28",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-select-default.json",
    ),
  ],
  "model.select_fast": [
    RowanActionClip(
      eventId: "model.select_fast",
      clipId: "cartesia-rowan-complete-pack/v1:model.select_fast",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-select-fast.wav",
      caption: "I'll use the faster route for this pass.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use after selecting a speed-prioritized model route.",
      trigger: "Use after selecting a speed-prioritized model route.",
      textSha256: "d7fb9221705869158ac3729df55c893f6fdfc2b740b23584efabf79cce879042",
      audioSha256: "6ca0cdc914b7223e386e3f545145e95c4b5343cc07c7b91ea56df50583574435",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-select-fast.json",
    ),
  ],
};
