import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData13 = <String, List<RowanActionClip>>{
  "operation.resumed": [
    RowanActionClip(
      eventId: "operation.resumed",
      clipId: "cartesia-rowan-action-pack/v1:operation.resumed",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-resumed.wav",
      caption: "I'm resuming the run.",
      category: "operation",
      context: "operation",
      prerequisite: "Use only after resume has been requested or accepted.",
      trigger: "Use only after resume has been requested or accepted.",
      textSha256: "62e3d8bd91d6fb3085fa8aadcf9c552c7e1a7f11bb2967b1332ac646918f52d6",
      audioSha256: "7de29eb6ccab54f907674fbf67c31ea3f1bc00971d4fe48d39c10d38eb33fa4f",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 2,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "operation.stopped": [
    RowanActionClip(
      eventId: "operation.stopped",
      clipId: "cartesia-rowan-action-pack/v1:operation.stopped",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-stopped.wav",
      caption: "I've stopped the run.",
      category: "operation",
      context: "operation",
      prerequisite: "Use only after stop/cancel is accepted or observed.",
      trigger: "Use only after stop/cancel is accepted or observed.",
      textSha256: "f73771f3b86c2f50f61203e46f7ae56e1b7d7581ef0e5d51c4d767bf4208687e",
      audioSha256: "cd6b4641d94bdd527fb2a96de9dd255b8d3faee1321b8e1c669842ac21e8c40d",
      durationSeconds: 1.04,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "operation.completed": [
    RowanActionClip(
      eventId: "operation.completed",
      clipId: "cartesia-rowan-action-pack/v1:operation.completed",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-completed.wav",
      caption: "The run has finished. The results are ready to inspect.",
      category: "operation",
      context: "operation",
      prerequisite: "Use for terminal operation completion; does not imply evaluation success.",
      trigger: "Use for terminal operation completion; does not imply evaluation success.",
      textSha256: "0e1ca9ef0970d1521af49086a80e4f4dd89173120a60f3bd976d32922da5712f",
      audioSha256: "2bb8a9658de42cedb541827bf4cf183854dff2d6b1d6faad29874918cfdc50ca",
      durationSeconds: 3.2,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "operation.unable_to_complete": [
    RowanActionClip(
      eventId: "operation.unable_to_complete",
      clipId: "cartesia-rowan-action-pack/v1:operation.unable_to_complete",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-unable-to-complete.wav",
      caption: "I wasn't able to complete that. You can review what happened.",
      category: "operation",
      context: "operation",
      prerequisite: "Use for terminal failure/blocker; preserve error details elsewhere.",
      trigger: "Use for terminal failure/blocker; preserve error details elsewhere.",
      textSha256: "fb90ff56c1b205e440cbe5f4caf94657674a5d92fcc9220adc636afe6af577fd",
      audioSha256: "4f6704e57045ea63381b261dd2aeda14b13509494d85a4c2edb200402e0cf490",
      durationSeconds: 3.52,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "connection.reconnecting": [
    RowanActionClip(
      eventId: "connection.reconnecting",
      clipId: "cartesia-rowan-action-pack/v1:connection.reconnecting",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-reconnecting.wav",
      caption: "I'm reconnecting to the run.",
      category: "connection",
      context: "connection",
      prerequisite: "Use only during actual reconnect/recovery attempt.",
      trigger: "Use only during actual reconnect/recovery attempt.",
      textSha256: "34d5b25a029e9a096ff198de4e5afa3ff6179b5d63f67cb12b6ebb598a4db417",
      audioSha256: "0208e80ad76aa74c444d47adbc9ee147c8bdc68eee56b12162c816a71312895c",
      durationSeconds: 2,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "connection.restored": [
    RowanActionClip(
      eventId: "connection.restored",
      clipId: "cartesia-rowan-action-pack/v1:connection.restored",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-connection-restored.wav",
      caption: "The connection is restored.",
      category: "connection",
      context: "connection",
      prerequisite: "Use only after connection or operation observation is restored.",
      trigger: "Use only after connection or operation observation is restored.",
      textSha256: "42080d9b098a471913e274c4b76a2e3a9910c35a2a88ffc5fe460c84e4a0bb4c",
      audioSha256: "88e40dc98debdbfab860869c2030e9d6114bedc3de91e9a45c1deb7d5ce8639d",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "listening.started": [
    RowanActionClip(
      eventId: "listening.started",
      clipId: "cartesia-rowan-action-pack/v1:listening.started",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-listening.wav",
      caption: "I'm listening.",
      category: "listening",
      context: "listening",
      prerequisite: "Use only when microphone/listening mode is actually enabled.",
      trigger: "Use only when microphone/listening mode is actually enabled.",
      textSha256: "df033aa56e248523a133a35557fc815f64f8beb9af04188522a9f03f4623188f",
      audioSha256: "71219455313ac6171191a7fd4c36172e84bf1e5ed63514a1abe810015d076225",
      durationSeconds: 0.96,
      recommendedCooldownSeconds: 2,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "screen_sharing.started": [
    RowanActionClip(
      eventId: "screen_sharing.started",
      clipId: "cartesia-rowan-action-pack/v1:screen_sharing.started",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-screen-sharing-started.wav",
      caption: "Screen sharing has started.",
      category: "screen_sharing",
      context: "screen_sharing",
      prerequisite: "Use only when screen sharing has actually started.",
      trigger: "Use only when screen sharing has actually started.",
      textSha256: "cc8f9c76a58f16e9b00c0a1c670087d366500edbb02b43ef93ac45896008a8da",
      audioSha256: "8af6d8eb9a921850984c510439db79c89133e050b12fe3a62d7f21dbeb87e08a",
      durationSeconds: 1.84,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "screen_sharing.stopped": [
    RowanActionClip(
      eventId: "screen_sharing.stopped",
      clipId: "cartesia-rowan-action-pack/v1:screen_sharing.stopped",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-screen-sharing-stopped.wav",
      caption: "Screen sharing has stopped.",
      category: "screen_sharing",
      context: "screen_sharing",
      prerequisite: "Use only when screen sharing has actually stopped.",
      trigger: "Use only when screen sharing has actually stopped.",
      textSha256: "3a36b46863952e11c76e84236018deca53963bb3fd19c37b86658732abc1a6ab",
      audioSha256: "7f61ed4f8240193f63f7924b1cf4439c9a7013c62a3c3d849f3af5ea5f3047a0",
      durationSeconds: 1.6,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "evaluation.finished": [
    RowanActionClip(
      eventId: "evaluation.finished",
      clipId: "cartesia-rowan-action-pack/v1:evaluation.finished",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-evaluation-finished.wav",
      caption: "The check has finished. You can review the result.",
      category: "evaluation",
      context: "evaluation",
      prerequisite: "Use when a named check reaches a terminal result; do not infer pass/safety.",
      trigger: "Use when a named check reaches a terminal result; do not infer pass/safety.",
      textSha256: "1c7349dad77d1e54f7d07e4b60db310bd9ccdac76bf3b9457e561d706b16294a",
      audioSha256: "e949d62210fc05a647228f32d3f4ac534373f87bf01318f7c717e2359a81621d",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "clarification.focus_first": [
    RowanActionClip(
      eventId: "clarification.focus_first",
      clipId: "cartesia-rowan-situational-pack/v1:clarification.focus_first",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-clarification-focus-first.wav",
      caption: "What would you like me to focus on first?",
      category: "clarification",
      context: "clarification",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "e5c1f251ea07b85510e01f37eea24b2fc0029004b157f53dc825ef94ea3dc46a",
      audioSha256: "edba8e4ed88651c6cab9c51909538bc3eb909be7d0e5c1978b49070e17157811",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "clarification.depth_choice": [
    RowanActionClip(
      eventId: "clarification.depth_choice",
      clipId: "cartesia-rowan-situational-pack/v1:clarification.depth_choice",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-clarification-depth-choice.wav",
      caption: "Do you want the short version or the detailed version?",
      category: "clarification",
      context: "clarification",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "2ec9707941ef5aecac48b4437ed1d5c44a19438c938e5bae198f3c58bb273804",
      audioSha256: "b1985d79c8a5b66e78c6aaaa78feda475e4d161086bd3b77e19e4366b3845704",
      durationSeconds: 2.96,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
};
