import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData9 = <String, List<RowanActionClip>>{
  "recovery.rollback_offer": [
    RowanActionClip(
      eventId: "recovery.rollback_offer",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.rollback_offer",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-rollback-offer.wav",
      caption: "I can roll back my last change.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use when rollback is possible and user choice is appropriate.",
      trigger: "Use when rollback is possible and user choice is appropriate.",
      textSha256: "23b5f0d663bef83df884032d544c2207e27119cebe6be7179fc8ee473dc97f69",
      audioSha256: "baa29ca12b28cde8225099dabc6f66bb3c8ebaeb1624b5b54344f950ab8cc36e",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-rollback-offer.json",
    ),
  ],
  "recovery.blocker_found": [
    RowanActionClip(
      eventId: "recovery.blocker_found",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.blocker_found",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-blocker-found.wav",
      caption: "I found a blocker that needs a decision.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after a blocker is identified and cannot be resolved autonomously.",
      trigger: "Use only after a blocker is identified and cannot be resolved autonomously.",
      textSha256: "dffdd4c9dcce3f83394288e506499edb39694c6df0a96281f065dfdbee88d969",
      audioSha256: "b33bdc61f2b1f1cab6950510ba8db24e71a5213508d2380cf92f46916e9daf9b",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/recovery-blocker-found.json",
    ),
  ],
  "recovery.permission_needed": [
    RowanActionClip(
      eventId: "recovery.permission_needed",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.permission_needed",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-permission-needed.wav",
      caption: "This needs a permission I do not have.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use when missing permission blocks the next step.",
      trigger: "Use when missing permission blocks the next step.",
      textSha256: "dd7f373b591014544df728df4c97879da9f32391ba0ecdf4973e62b622aca1a1",
      audioSha256: "58f9a387a10ace4045209dc80816a02bd62b2774b033781d08b060ea010d55e3",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/recovery-permission-needed.json",
    ),
  ],
  "recovery.path_missing": [
    RowanActionClip(
      eventId: "recovery.path_missing",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.path_missing",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-path-missing.wav",
      caption: "That path is not available here.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after checking the path is unavailable.",
      trigger: "Use only after checking the path is unavailable.",
      textSha256: "c27f2986e701e5d9394e4620b5c55f02394fac9b664bacbe24efeea5570f2243",
      audioSha256: "27c1ef7a062b5a9c4e167f3e7c5957db0ceef5cbae8c5aafb8045a6f9e998662",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-path-missing.json",
    ),
  ],
  "recovery.file_changed": [
    RowanActionClip(
      eventId: "recovery.file_changed",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.file_changed",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-file-changed.wav",
      caption: "The file changed while I was working.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after detecting a concurrent file change.",
      trigger: "Use only after detecting a concurrent file change.",
      textSha256: "a609e2885f7fec390f71d6dda332e782670ed80f8d84d6492157d1e6b1a5427d",
      audioSha256: "543efe7956448a3e7a04e6981142767890d4e3525bcbf008619c6f092527d71f",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/recovery-file-changed.json",
    ),
  ],
  "recovery.conflict_detected": [
    RowanActionClip(
      eventId: "recovery.conflict_detected",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.conflict_detected",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-conflict-detected.wav",
      caption: "There is a conflict to resolve.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after a conflict is detected.",
      trigger: "Use only after a conflict is detected.",
      textSha256: "a27868fb962b695ff33d59deced834e51c81f096f1385a63cf932461d8bf1c0e",
      audioSha256: "f76aee9b7615b8325cceeb0d1abea7da64ef193a8fe0d7320a175c779495205f",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/recovery-conflict-detected.json",
    ),
  ],
  "recovery.service_down": [
    RowanActionClip(
      eventId: "recovery.service_down",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.service_down",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-service-down.wav",
      caption: "The service is not responding right now.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after a service call fails or times out.",
      trigger: "Use only after a service call fails or times out.",
      textSha256: "57348ae35c6d66e0f30e6b9bf9a83d5f89e7e97fbdfde42d5d89e222002ccf41",
      audioSha256: "cc428e58fc636fbc43c88e03704c3f7018af602565db36a09fb34efd166dfa2a",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-service-down.json",
    ),
  ],
  "recovery.resume_point": [
    RowanActionClip(
      eventId: "recovery.resume_point",
      clipId: "cartesia-rowan-complete-pack/v1:recovery.resume_point",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/recovery-resume-point.wav",
      caption: "I have a clear point to resume from.",
      category: "errors_recovery",
      context: "errors_recovery",
      prerequisite: "Use only after a resumable point has been identified.",
      trigger: "Use only after a resumable point has been identified.",
      textSha256: "374354c97f970b2ffadeaddad4f6dd7ab2f3460042aa019e3818657df2a1a6af",
      audioSha256: "c3f8738d15796eac52b38bb7679aa9d5f3de41b13d742209eb83f87986af52f1",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/recovery-resume-point.json",
    ),
  ],
  "longtask.estimate": [
    RowanActionClip(
      eventId: "longtask.estimate",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.estimate",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-estimate.wav",
      caption: "I'll give you a quick estimate before the long run.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use before a long-running task where time or budget matters.",
      trigger: "Use before a long-running task where time or budget matters.",
      textSha256: "9c55d1f43d7a7ea17fcbbada8747a097798f3feddfce076a0118083a79903ce9",
      audioSha256: "0f96150d4c76330a5433245a93f5d7b356bddd3596be29a4248e3940956577a9",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/longtask-estimate.json",
    ),
  ],
  "longtask.checkpoint": [
    RowanActionClip(
      eventId: "longtask.checkpoint",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.checkpoint",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-checkpoint.wav",
      caption: "I'll leave a checkpoint before continuing.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use before continuing a long task across a boundary.",
      trigger: "Use before continuing a long task across a boundary.",
      textSha256: "2bf123a5ca727af5e37b84bc4e354f7604d5c7f24f96920bad2b5d65dae3582e",
      audioSha256: "e8187cc9f6a88fae2d57cbeffbb4d479efacdcaeef73042a027f0ed0e67bed92",
      durationSeconds: 2.08,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/longtask-checkpoint.json",
    ),
  ],
  "longtask.progress_digest": [
    RowanActionClip(
      eventId: "longtask.progress_digest",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.progress_digest",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-progress-digest.wav",
      caption: "I'll keep the next update focused.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use when progress updates should stay brief.",
      trigger: "Use when progress updates should stay brief.",
      textSha256: "061b8206eef0caaaf1b87b3f5ab0d26714cc754df2b21291e285fa8e4cfe143d",
      audioSha256: "f069786664c2dd89105b1d7a5420080e5e1ab5f78a8451878143d659ac52d4f2",
      durationSeconds: 2.08,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/longtask-progress-digest.json",
    ),
  ],
  "longtask.cost_warning": [
    RowanActionClip(
      eventId: "longtask.cost_warning",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.cost_warning",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-cost-warning.wav",
      caption: "This may use more of the run budget.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use before a potentially expensive or long batch.",
      trigger: "Use before a potentially expensive or long batch.",
      textSha256: "e51cdf7b5848817ab834fd6e9d3b6e3290f91222517dddc761afc97a15a16b6c",
      audioSha256: "2b7eff31c40ab0152910b72389a362c23ee2816f65a676d8775ce3d034bfae10",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/longtask-cost-warning.json",
    ),
  ],
};
