import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData4 = <String, List<RowanActionClip>>{
  "orchestration.one_route_blocked": [
    RowanActionClip(
      eventId: "orchestration.one_route_blocked",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.one_route_blocked",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-one-route-blocked.wav",
      caption: "One route is blocked, so I'll continue with the usable path.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use only after one route is unavailable and another remains valid.",
      trigger: "Use only after one route is unavailable and another remains valid.",
      textSha256: "3a69fef7249ba67da2515a11ac16c6f40f6ebbe991639bd2648556c54537be42",
      audioSha256: "0af498fc0ac132eb30df24b76378303d276e8e9028bced024576c5aeabc203f7",
      durationSeconds: 3.84,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/orchestration-one-route-blocked.json",
    ),
  ],
  "orchestration.merge_findings": [
    RowanActionClip(
      eventId: "orchestration.merge_findings",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.merge_findings",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-merge-findings.wav",
      caption: "I'll merge only the parts that check out.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use before combining multi-route findings after verification.",
      trigger: "Use before combining multi-route findings after verification.",
      textSha256: "a3500e6f4b838f1812fc54edacabc62a8ea642c50c026a11b9041d0f6a500b72",
      audioSha256: "61b1d76f26e3d1a2ba947213390feb584163e2feb0ac3290ade7c27cbdce5f20",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/orchestration-merge-findings.json",
    ),
  ],
  "orchestration.handoff_ready": [
    RowanActionClip(
      eventId: "orchestration.handoff_ready",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.handoff_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-handoff-ready.wav",
      caption: "This is ready for another route to pick up.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use after preparing a handoff packet for another route.",
      trigger: "Use after preparing a handoff packet for another route.",
      textSha256: "f3be4976471924b5b33c5accb04f13274868485360d0c8fe27758968edbe8ffe",
      audioSha256: "a4d83da8212aa42c964d273bdc79dd0a50820e76c1ac6a2ab406e8193fb90069",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/orchestration-handoff-ready.json",
    ),
  ],
  "orchestration.route_idle": [
    RowanActionClip(
      eventId: "orchestration.route_idle",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.route_idle",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-route-idle.wav",
      caption: "That route is idle now.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use only after a route is observed idle or no longer running.",
      trigger: "Use only after a route is observed idle or no longer running.",
      textSha256: "0eee253771d5d52fa5ff646956661012c7c7e1ef0d3c7fc2ce2a4b2c91472fc0",
      audioSha256: "c3d531ae82e7fa7eb1e3ac82a2f689c08a65883383e3fabcd896f3d0df38de89",
      durationSeconds: 1.6,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/orchestration-route-idle.json",
    ),
  ],
  "orchestration.route_budget": [
    RowanActionClip(
      eventId: "orchestration.route_budget",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.route_budget",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-route-budget.wav",
      caption: "I'll keep the route inside the budget you set.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use when a budget or limit exists for routed work.",
      trigger: "Use when a budget or limit exists for routed work.",
      textSha256: "2aeb239381c41341df51ce89ec4833fb1965188a0d16806d1de2e7bbd94647ea",
      audioSha256: "f35defcc7b2dc2947244a52161a6afe7403a83330d60794f1a42c89b0032c38c",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/orchestration-route-budget.json",
    ),
  ],
  "orchestration.no_consensus": [
    RowanActionClip(
      eventId: "orchestration.no_consensus",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.no_consensus",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-no-consensus.wav",
      caption: "These results need another check.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use after comparing route outputs that do not support a firm conclusion.",
      trigger: "Use after comparing route outputs that do not support a firm conclusion.",
      textSha256: "eb2b1cad327f9545c92aaa72d862575d2e51a3380ef778bc9caf17925ad4b208",
      audioSha256: "903b182cb1106e986fa465fb9f22326b36285717e16f4c14d1389df13ce6e2dc",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/orchestration-no-consensus.json",
    ),
  ],
  "privacy.live_screen_offer": [
    RowanActionClip(
      eventId: "privacy.live_screen_offer",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.live_screen_offer",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-live-screen-offer.wav",
      caption: "I can use Live Screen if you turn it on.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use when Live Screen would help but is not enabled by Rowan.",
      trigger: "Use when Live Screen would help but is not enabled by Rowan.",
      textSha256: "ac976a4c395ef471117017501b5ee6060eab4ee90ab67a524ed6d509e1e9b03d",
      audioSha256: "d14245b5a5ba56f8a70a549746bcf47d0a532be78f48f3e84b788711941a819c",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/privacy-live-screen-offer.json",
    ),
  ],
  "privacy.live_screen_off": [
    RowanActionClip(
      eventId: "privacy.live_screen_off",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.live_screen_off",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-live-screen-off.wav",
      caption: "Live Screen is off.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use only when Live Screen state is known to be off.",
      trigger: "Use only when Live Screen state is known to be off.",
      textSha256: "73b03c42ab7b8f1d180df57259ef3773b209f9c1b02a8f0cfc6289330f326c34",
      audioSha256: "1d101a967efca6bc91606db7b9299f6647b2358d07c3600d7fbcfb578c753c4a",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/privacy-live-screen-off.json",
    ),
  ],
  "privacy.live_screen_on": [
    RowanActionClip(
      eventId: "privacy.live_screen_on",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.live_screen_on",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-live-screen-on.wav",
      caption: "Live Screen is available for this task.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use only when Live Screen is enabled for the current task.",
      trigger: "Use only when Live Screen is enabled for the current task.",
      textSha256: "47cc85b519911fade1284fb373741cc6324a4ca1d04c2dabcbafedeff8fcf20f",
      audioSha256: "2ea375146c0eece655b070386f55abc9bff3780dc0aab3abfddec6007d9c7834",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/privacy-live-screen-on.json",
    ),
  ],
  "privacy.screen_scope": [
    RowanActionClip(
      eventId: "privacy.screen_scope",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.screen_scope",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-screen-scope.wav",
      caption: "I'll work only with the screen content you share.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use when clarifying screen-sharing scope.",
      trigger: "Use when clarifying screen-sharing scope.",
      textSha256: "410859d822669d69151535a131472495415a2286baf2e3713047fc5fb98a47c5",
      audioSha256: "d03a0d347ca1d50a9c29a7782ceb97e89773b0bb25a53a7e5502f53a3ce54a68",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-screen-scope.json",
    ),
  ],
  "privacy.private_window_boundary": [
    RowanActionClip(
      eventId: "privacy.private_window_boundary",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.private_window_boundary",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-private-window-boundary.wav",
      caption: "I won't use private windows unless you bring them into scope.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use when setting browser or screen boundaries.",
      trigger: "Use when setting browser or screen boundaries.",
      textSha256: "cd46a0fb55be72011264c55d1716544751805e55eca96d8f0310d088ae154ddf",
      audioSha256: "a5b1ad18b868ad4eaf4ebd81a335e84d74855b8ea81f275b81fe6b1de6627f3a",
      durationSeconds: 3.6,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/privacy-private-window-boundary.json",
    ),
  ],
  "privacy.microphone_off": [
    RowanActionClip(
      eventId: "privacy.microphone_off",
      clipId: "cartesia-rowan-complete-pack/v1:privacy.microphone_off",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/privacy-microphone-off.wav",
      caption: "Voice input is off.",
      category: "privacy_livescreen",
      context: "privacy_livescreen",
      prerequisite: "Use only when microphone or voice input state is known to be off.",
      trigger: "Use only when microphone or voice input state is known to be off.",
      textSha256: "b72a3f4091cb074f790c69da6105106517ed21fe3a10113dcb4c3b48f1232ee4",
      audioSha256: "6539c56e9d131c24945c02a58d2b7c9a083a2c02ce03f409bff0dd291705548b",
      durationSeconds: 1.44,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/privacy-microphone-off.json",
    ),
  ],
};
