import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData16 = <String, List<RowanActionClip>>{
  "check.inconclusive": [
    RowanActionClip(
      eventId: "check.inconclusive",
      clipId: "cartesia-rowan-situational-pack/v1:check.inconclusive",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-check-inconclusive.wav",
      caption: "The check is inconclusive. The record is ready to inspect.",
      category: "check",
      context: "check",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "2f21dc9bbb5ccbab5a6f66e3f08ceb84a733fbccc4b7f6bc18a27ff2e4fa85fb",
      audioSha256: "2237d0ff57390741cda03aa6a535bd1dabef2952432e3e602e38a62e3dc2b120",
      durationSeconds: 3.6,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "receipt.saved": [
    RowanActionClip(
      eventId: "receipt.saved",
      clipId: "cartesia-rowan-situational-pack/v1:receipt.saved",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-receipt-saved.wav",
      caption: "I saved the receipt for this step.",
      category: "receipt",
      context: "receipt",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "873a41d54c0bf1efb64a1a766f2a8e7b80ad4e5653ecb1b796155a283a9a2cd4",
      audioSha256: "ee833c0dcdbadd20104ff7f65344b9fcae0c2b8fff2a548b4fd871e25092779a",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "replay.label_visible": [
    RowanActionClip(
      eventId: "replay.label_visible",
      clipId: "cartesia-rowan-situational-pack/v1:replay.label_visible",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-replay-label-visible.wav",
      caption: "I'll keep the replay label visible.",
      category: "replay",
      context: "replay",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "6bcebacda774dedf9fe40b1dc448ff77ed627bd8d77c39e04f3e4bc3c168adde",
      audioSha256: "1d555e7d82ce7c64539718fa5d8e4a1c43f0a1825dd2509bd84e8edf97ae094b",
      durationSeconds: 2,
      recommendedCooldownSeconds: 4,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "thanks.keep_going": [
    RowanActionClip(
      eventId: "thanks.keep_going",
      clipId: "cartesia-rowan-situational-pack/v1:thanks.keep_going",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-thanks-keep-going.wav",
      caption: "Thanks. I'll keep going.",
      category: "thanks",
      context: "thanks",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "9322cb93754d429828cdf1ef389a16b19679246bd7ce44741bec3e19f1b2892b",
      audioSha256: "a80d8385e055b208473b4669005bf993309bb6a57078d1fc9c7d65bcd223d1fd",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "thanks.welcome": [
    RowanActionClip(
      eventId: "thanks.welcome",
      clipId: "cartesia-rowan-situational-pack/v1:thanks.welcome",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-youre-welcome.wav",
      caption: "You're welcome.",
      category: "thanks",
      context: "thanks",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "124eb273f9a0a470e3d6930f97e1402f311a753dc9d656b1ef17ef12367caffa",
      audioSha256: "09cb706a794e8329e6a80cc838a7cd5f77eef04c6ee3949eb173f4574552f820",
      durationSeconds: 0.8,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "clarification.helps_continue": [
    RowanActionClip(
      eventId: "clarification.helps_continue",
      clipId: "cartesia-rowan-situational-pack/v1:clarification.helps_continue",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-situational-pack-helps-continue.wav",
      caption: "That helps. I'll continue from there.",
      category: "clarification",
      context: "clarification",
      prerequisite: "See source manifest",
      trigger: "See source manifest",
      textSha256: "b59c125c4aec66e93c6d2c6d65949db6941d959d8e0fe8f43ad5c8ccc9d97889",
      audioSha256: "9b64871d67a5407a5210e045f9273fa8de52a497d3f9561df1f1a2c5fa4da864",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-situational-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
};
