import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData7 = <String, List<RowanActionClip>>{
  "code.tool_call": [
    RowanActionClip(
      eventId: "code.tool_call",
      clipId: "cartesia-rowan-complete-pack/v1:code.tool_call",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-tool-call.wav",
      caption: "I'll use the existing tool for that.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before calling an existing helper or repo tool.",
      trigger: "Use before calling an existing helper or repo tool.",
      textSha256: "cd4323611a9519b082186797666328be70da919ed4b4f6c807c455d122049f8a",
      audioSha256: "ea7ca0c5b2d1f4219d49b8b136481ddf7e0d3c565e1b89de735830d6a36c86fc",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/code-tool-call.json",
    ),
  ],
  "code.no_new_tool": [
    RowanActionClip(
      eventId: "code.no_new_tool",
      clipId: "cartesia-rowan-complete-pack/v1:code.no_new_tool",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-no-new-tool.wav",
      caption: "The existing tool covers this case.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use after confirming existing tooling is enough.",
      trigger: "Use after confirming existing tooling is enough.",
      textSha256: "a9ce8d962145c6a9d5503302e7a21fad5387abbddd202a7516bf2294fcca41cb",
      audioSha256: "255dba03c6d403cc6440dd8a21dccb637879a0be5f215ab86cd8c2277442bbaa",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/code-no-new-tool.json",
    ),
  ],
  "code.config_read": [
    RowanActionClip(
      eventId: "code.config_read",
      clipId: "cartesia-rowan-complete-pack/v1:code.config_read",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-config-read.wav",
      caption: "I'll read the config before changing it.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before config edits or config-dependent claims.",
      trigger: "Use before config edits or config-dependent claims.",
      textSha256: "f5f571fa4ab0b31ae98b03538fcff3da2066991d808308795fd0e691751d3ae6",
      audioSha256: "6f21cd9e3db676211ffbff883ed178d3248428f56cf378915d6ef30d73a56798",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/code-config-read.json",
    ),
  ],
  "code.dependency_check": [
    RowanActionClip(
      eventId: "code.dependency_check",
      clipId: "cartesia-rowan-complete-pack/v1:code.dependency_check",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-dependency-check.wav",
      caption: "I'll check the dependency version first.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before relying on a dependency capability.",
      trigger: "Use before relying on a dependency capability.",
      textSha256: "1b117d6a4f02a1f7ba0b769a8d98e8ca7f1c8f14edf67dfbfac3d428edbe9266",
      audioSha256: "22f5daa966bd5daeaed600dc9383c06b9bc8d33f151bd1833cf4d8ed9133958b",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/code-dependency-check.json",
    ),
  ],
  "code.branch_needed": [
    RowanActionClip(
      eventId: "code.branch_needed",
      clipId: "cartesia-rowan-complete-pack/v1:code.branch_needed",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-branch-needed.wav",
      caption: "This needs a separate worktree before edits.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use when ownership or isolation requires a separate worktree.",
      trigger: "Use when ownership or isolation requires a separate worktree.",
      textSha256: "54258733f67dd7dd58096577e179f5796b326a0dd94052787280fda30e902ae9",
      audioSha256: "6192e94090911791666019c4e6aaf632d591b56945b46713f279e903adcdefe7",
      durationSeconds: 3.04,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/code-branch-needed.json",
    ),
  ],
  "code.diff_review": [
    RowanActionClip(
      eventId: "code.diff_review",
      clipId: "cartesia-rowan-complete-pack/v1:code.diff_review",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-diff-review.wav",
      caption: "I'll review the diff before I call it done.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before completion claims for code changes.",
      trigger: "Use before completion claims for code changes.",
      textSha256: "cb4f0f33e21b97a334a334a33af60749fe307a70910a1b0609b66cd31154bdf4",
      audioSha256: "e6fd6e80c6334a0d61b9e121da9c06290a8584b0dbcb8117948492797dd89d77",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/code-diff-review.json",
    ),
  ],
  "verify.claim_check": [
    RowanActionClip(
      eventId: "verify.claim_check",
      clipId: "cartesia-rowan-complete-pack/v1:verify.claim_check",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-claim-check.wav",
      caption: "I'll check the claim against a source.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use before verifying a factual claim.",
      trigger: "Use before verifying a factual claim.",
      textSha256: "d476b460d88f4e8c74c504a2a9afafdc1f0e8ef0e76c04d8269baf2799bfbd62",
      audioSha256: "2be63db334ff6affb4aba57b814835f2d17f72a910d6e671a947cc66c6c35196",
      durationSeconds: 2,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-claim-check.json",
    ),
  ],
  "verify.source_opened": [
    RowanActionClip(
      eventId: "verify.source_opened",
      clipId: "cartesia-rowan-complete-pack/v1:verify.source_opened",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-source-opened.wav",
      caption: "The source is open for review.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use only after the source is opened or available to inspect.",
      trigger: "Use only after the source is opened or available to inspect.",
      textSha256: "4c421217e40d937fc98c71632a374dfa1562801a164a5c6835b7f6fd43a8d91b",
      audioSha256: "0512c5446a4953cf031412f5c27837b5e9288694a9b8d30e074b64e0a6fa0a9b",
      durationSeconds: 1.84,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/verify-source-opened.json",
    ),
  ],
  "verify.command_run": [
    RowanActionClip(
      eventId: "verify.command_run",
      clipId: "cartesia-rowan-complete-pack/v1:verify.command_run",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-command-run.wav",
      caption: "I'll run the check for that.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use before running a command intended to verify a claim.",
      trigger: "Use before running a command intended to verify a claim.",
      textSha256: "541bd8d9d3b1c487002413694f6c8c6a1e7c7a25469a7140cca6e546873a26e0",
      audioSha256: "9f0df8baf56302b082e21981e555247fca7dc6de3a5e2513b44c4d5d0d8cf396",
      durationSeconds: 1.44,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/verify-command-run.json",
    ),
  ],
  "verify.output_captured": [
    RowanActionClip(
      eventId: "verify.output_captured",
      clipId: "cartesia-rowan-complete-pack/v1:verify.output_captured",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-output-captured.wav",
      caption: "The command output is captured.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use only after command output has been captured in the record.",
      trigger: "Use only after command output has been captured in the record.",
      textSha256: "18e02aca4ed76cb468141ceb21ea24628d607925b419869f25e048df2312e891",
      audioSha256: "b79f3b3f80b581a26665b1c49c0dce40ce0e2b1200e821df31a82862689bac6c",
      durationSeconds: 1.84,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/verify-output-captured.json",
    ),
  ],
  "verify.hash_planned": [
    RowanActionClip(
      eventId: "verify.hash_planned",
      clipId: "cartesia-rowan-complete-pack/v1:verify.hash_planned",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-hash-planned.wav",
      caption: "I'll calculate the hash before comparing files.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use before byte or artifact hash comparison.",
      trigger: "Use before byte or artifact hash comparison.",
      textSha256: "294ab0e85e868db2bb85b095d94232e1b5db31f1a36b0e3c24b72a9f01d3e1a4",
      audioSha256: "7504c06a691d99a740a5afa92b25ce95c873d00a566135e4d4e83d99c630909d",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/verify-hash-planned.json",
    ),
  ],
  "verify.hash_ready": [
    RowanActionClip(
      eventId: "verify.hash_ready",
      clipId: "cartesia-rowan-complete-pack/v1:verify.hash_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/verify-hash-ready.wav",
      caption: "The hash is ready to compare.",
      category: "verification_receipts",
      context: "verification_receipts",
      prerequisite: "Use only after a hash has been calculated.",
      trigger: "Use only after a hash has been calculated.",
      textSha256: "261164ee7a4cf03bd8ff953858a8e6cc5d8831a417dd842b5c759173e4db321a",
      audioSha256: "d28f9415b165b22dc5313ed869c0007963f9f7332dc2221fb55d7a87d2cf21e4",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/verify-hash-ready.json",
    ),
  ],
};
