import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData10 = <String, List<RowanActionClip>>{
  "longtask.cost_stop": [
    RowanActionClip(
      eventId: "longtask.cost_stop",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.cost_stop",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-cost-stop.wav",
      caption: "I'll stop before crossing the limit.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use when a budget, time, or usage limit is set.",
      trigger: "Use when a budget, time, or usage limit is set.",
      textSha256: "6ef603dea89e5994a349bbd01e7589bd7d43dfd0de1c799334b1e3b83999c9e3",
      audioSha256: "0ef85ffb35bcc20fafd40d76c609db38f92875fe40b56687eb99c8221ec85b59",
      durationSeconds: 2,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/longtask-cost-stop.json",
    ),
  ],
  "longtask.batch_ready": [
    RowanActionClip(
      eventId: "longtask.batch_ready",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.batch_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-batch-ready.wav",
      caption: "This is ready to run as a batch.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use only after batch inputs are prepared.",
      trigger: "Use only after batch inputs are prepared.",
      textSha256: "763dc7a6506ba08ce9ae7e35a7285b06b7fa303c5c5ac1117f72799bbf8e136c",
      audioSha256: "ff0e2a219ff3cbf3bc654a33c62e7ad834968b58dbc1484569c869a7c103c58f",
      durationSeconds: 2,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/longtask-batch-ready.json",
    ),
  ],
  "longtask.batch_pause": [
    RowanActionClip(
      eventId: "longtask.batch_pause",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.batch_pause",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-batch-pause.wav",
      caption: "I can pause the batch after this item.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use when pausing after a current batch item is possible.",
      trigger: "Use when pausing after a current batch item is possible.",
      textSha256: "69dfa822e12394a657b575732a954b5280ddcb6f7034cb05a352feabb5e17092",
      audioSha256: "4e1b0baa2cb0161d6156bf6add6ccb33cee183f3f60f790edb84036e15f6aaa5",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 60,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/longtask-batch-pause.json",
    ),
  ],
  "longtask.quiet_mode": [
    RowanActionClip(
      eventId: "longtask.quiet_mode",
      clipId: "cartesia-rowan-complete-pack/v1:longtask.quiet_mode",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/longtask-quiet-mode.wav",
      caption: "I can stay quiet until something changes.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use when offering quiet monitoring or reduced updates.",
      trigger: "Use when offering quiet monitoring or reduced updates.",
      textSha256: "5d0fea22e08202e0f1942d55507a027737cd1d4afebbe1d462ff97d9e0c26674",
      audioSha256: "3b67d5e17269259f4159be56762329f8c1beb686c4c9c1fee473968fe0b5f37d",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 120,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/longtask-quiet-mode.json",
    ),
  ],
  "accessibility.captions_on": [
    RowanActionClip(
      eventId: "accessibility.captions_on",
      clipId: "cartesia-rowan-complete-pack/v1:accessibility.captions_on",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/accessibility-captions-on.wav",
      caption: "Captions are on.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use only after captions are enabled.",
      trigger: "Use only after captions are enabled.",
      textSha256: "3197925268fd099c22d321e140f67e730c0915b494ac5bc628e7724418694b6a",
      audioSha256: "e64883d69f47b79e2db8def6061063af7f8f39ee7fce89796579f77d0b332a6c",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/accessibility-captions-on.json",
    ),
  ],
  "accessibility.captions_off": [
    RowanActionClip(
      eventId: "accessibility.captions_off",
      clipId: "cartesia-rowan-complete-pack/v1:accessibility.captions_off",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/accessibility-captions-off.wav",
      caption: "Captions are off.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use only after captions are disabled.",
      trigger: "Use only after captions are disabled.",
      textSha256: "88e3dcdc4b29216052a15243eb70bf2cbbe493d21a428719ecf693479823305e",
      audioSha256: "41ce45e6914e7cc803f4ecee02285adb61ee13272d9fb73dfa65d2b8e8d414a6",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/accessibility-captions-off.json",
    ),
  ],
  "accessibility.reduce_motion": [
    RowanActionClip(
      eventId: "accessibility.reduce_motion",
      clipId: "cartesia-rowan-complete-pack/v1:accessibility.reduce_motion",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/accessibility-reduce-motion.wav",
      caption: "I can reduce motion for this view.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use when offering reduced motion settings.",
      trigger: "Use when offering reduced motion settings.",
      textSha256: "d9dcd032bacf5c85072ade534b1b99f0144363461ed1e2cb86df5848a15d6418",
      audioSha256: "697870972be63e00cee5b2dd17d521a167d35cef3820fd745ebc0df5bdde9b2d",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/accessibility-reduce-motion.json",
    ),
  ],
  "accessibility.high_contrast": [
    RowanActionClip(
      eventId: "accessibility.high_contrast",
      clipId: "cartesia-rowan-complete-pack/v1:accessibility.high_contrast",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/accessibility-high-contrast.wav",
      caption: "I can switch to a higher contrast view.",
      category: "long_tasks_limits_accessibility",
      context: "long_tasks_limits_accessibility",
      prerequisite: "Use when offering higher contrast display settings.",
      trigger: "Use when offering higher contrast display settings.",
      textSha256: "5a86820a1de8bf9e3c49db947b4580fbfb9dbfb345bdcefd6a32d21737cad6c3",
      audioSha256: "17ace5d042baa67df0d019d21fd4ad8913a8f19fa772cbc44c760c821d6ddd8a",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/accessibility-high-contrast.json",
    ),
  ],
  "export.prepare": [
    RowanActionClip(
      eventId: "export.prepare",
      clipId: "cartesia-rowan-complete-pack/v1:export.prepare",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-prepare.wav",
      caption: "I'll prepare the export.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use before creating an export artifact.",
      trigger: "Use before creating an export artifact.",
      textSha256: "a1bfc55f3bfc07ef893726b241f1eed22ffe5739d891bc65c04da450569f2209",
      audioSha256: "5a5e445abde1bc7e6042cd14ff5961cec1a8ca0155f62c7149ac457730e7c0f8",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/export-prepare.json",
    ),
  ],
  "export.ready": [
    RowanActionClip(
      eventId: "export.ready",
      clipId: "cartesia-rowan-complete-pack/v1:export.ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-ready.wav",
      caption: "The export is ready to review.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use only after the export file exists.",
      trigger: "Use only after the export file exists.",
      textSha256: "ed434798b168d63f02f3a815b224aff034cb0c5692ce761a29714fd56542f0b9",
      audioSha256: "fce5b40797f8bec0fd7127a5799b73ddfd0d525a67545ad4b67cc979050acbe6",
      durationSeconds: 2.16,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/export-ready.json",
    ),
  ],
  "export.format_choose": [
    RowanActionClip(
      eventId: "export.format_choose",
      clipId: "cartesia-rowan-complete-pack/v1:export.format_choose",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-format-choose.wav",
      caption: "Which format should I prepare?",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use when choosing between supported export formats.",
      trigger: "Use when choosing between supported export formats.",
      textSha256: "f4dcaf566c2935e48e4633159c8e55d66eebba6ee07785e13cf1e817da222664",
      audioSha256: "aafba9dc118d5827ff8157e49994f50d5c5281e9d5b1504da5ee417778f12526",
      durationSeconds: 1.68,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/export-format-choose.json",
    ),
  ],
  "export.pdf_ready": [
    RowanActionClip(
      eventId: "export.pdf_ready",
      clipId: "cartesia-rowan-complete-pack/v1:export.pdf_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/export-pdf-ready.wav",
      caption: "The PDF is ready to review.",
      category: "exports_presentations",
      context: "exports_presentations",
      prerequisite: "Use only after the PDF exists.",
      trigger: "Use only after the PDF exists.",
      textSha256: "c57c43add0a14e1a6d517f998331dae05207b29484b2d4d014128b9c2a877721",
      audioSha256: "2aa3018562edae9229cf00a9a40b6d185f0b0cf47fd27101187fd000eab72922",
      durationSeconds: 1.92,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/export-pdf-ready.json",
    ),
  ],
};
