import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData3 = <String, List<RowanActionClip>>{
  "model.select_deep": [
    RowanActionClip(
      eventId: "model.select_deep",
      clipId: "cartesia-rowan-complete-pack/v1:model.select_deep",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-select-deep.wav",
      caption: "I'll use the deeper route for this pass.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use after selecting a reasoning-prioritized model route.",
      trigger: "Use after selecting a reasoning-prioritized model route.",
      textSha256: "bee6003fd612547310eb4843268c4f3fc2570863cb6c6cddafd940bd077cead6",
      audioSha256: "acb6a2dc39f63cc826e0d46e908a523960721b20fedcbbb61b65f07a8d3d02e4",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-select-deep.json",
    ),
  ],
  "model.provider_choose": [
    RowanActionClip(
      eventId: "model.provider_choose",
      clipId: "cartesia-rowan-complete-pack/v1:model.provider_choose",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-provider-choose.wav",
      caption: "I can switch providers if the task needs it.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use when offering provider routing without changing state yet.",
      trigger: "Use when offering provider routing without changing state yet.",
      textSha256: "3ed286e59b73cfe90d3f04994eb54bdd8ddfdd42af42024582704ddd81dd654a",
      audioSha256: "50132b6a08ce812afff06c557073877b2dfa59c2b2087aafc7ef44bcc14d04ac",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-provider-choose.json",
    ),
  ],
  "model.local_available": [
    RowanActionClip(
      eventId: "model.local_available",
      clipId: "cartesia-rowan-complete-pack/v1:model.local_available",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-local-available.wav",
      caption: "I can use the local route when it is available.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use when local model routing is an option, before claiming it is active.",
      trigger: "Use when local model routing is an option, before claiming it is active.",
      textSha256: "b3c369fdb39f6a1d97aff0990f1e59119f1b425bd1d3b4fa478ab43761c224d7",
      audioSha256: "70a01295a4f17f829d7f444046f4fe53276c3e15a643d2242dd077e7c68aab80",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-local-available.json",
    ),
  ],
  "model.remote_boundary": [
    RowanActionClip(
      eventId: "model.remote_boundary",
      clipId: "cartesia-rowan-complete-pack/v1:model.remote_boundary",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-remote-boundary.wav",
      caption: "I can keep this task on the local route.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use when explaining or confirming remote-provider restraint.",
      trigger: "Use when explaining or confirming remote-provider restraint.",
      textSha256: "619b622d2bf3cf1680d0ae9f5005b1dedd0523011d2eb805e20832cf362a42ae",
      audioSha256: "1a468cf111972809ca70b06bcd945187b7132304c9474384c4656c3b6128e9a3",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/model-remote-boundary.json",
    ),
  ],
  "model.model_limit": [
    RowanActionClip(
      eventId: "model.model_limit",
      clipId: "cartesia-rowan-complete-pack/v1:model.model_limit",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-model-limit.wav",
      caption: "That model may have a tighter context window.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use when a selected model could affect context capacity.",
      trigger: "Use when a selected model could affect context capacity.",
      textSha256: "1153d7080be8ac6a7a17d546cd40d328dc0008451a5e96398a59828b62cf160f",
      audioSha256: "a40eb03d3125a60d86c7e0b782afdaef5b402db0a80553d79502dc060a0d185c",
      durationSeconds: 2.96,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-model-limit.json",
    ),
  ],
  "model.capability_check": [
    RowanActionClip(
      eventId: "model.capability_check",
      clipId: "cartesia-rowan-complete-pack/v1:model.capability_check",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-capability-check.wav",
      caption: "I'll check what this model can actually do.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use before verifying tool, context, or modality support.",
      trigger: "Use before verifying tool, context, or modality support.",
      textSha256: "478a5efe202db699430c58ffb94632ad998ebe3c6f6f1d6d5170ddb0164e05fd",
      audioSha256: "3b391cc8f50b61bbe22b090f06678af6abb937e096053a42141ca16d0afa7f42",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-capability-check.json",
    ),
  ],
  "model.fallback_ready": [
    RowanActionClip(
      eventId: "model.fallback_ready",
      clipId: "cartesia-rowan-complete-pack/v1:model.fallback_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-fallback-ready.wav",
      caption: "I can fall back to another route if this one stalls.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use before switching routes after latency or failure.",
      trigger: "Use before switching routes after latency or failure.",
      textSha256: "720570f5667abee76f26b76b930dc2170261951138a9e2814a8bdfc6eff5691a",
      audioSha256: "de823f4550b5a8d1e672ee4d80959e3b81c2b912befa7a9f06e6da7f10403d4a",
      durationSeconds: 3.44,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-fallback-ready.json",
    ),
  ],
  "model.provider_receipt": [
    RowanActionClip(
      eventId: "model.provider_receipt",
      clipId: "cartesia-rowan-complete-pack/v1:model.provider_receipt",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/model-provider-receipt.wav",
      caption: "I'll record which route produced the result.",
      category: "model_provider",
      context: "model_provider",
      prerequisite: "Use before logging provider or model provenance for a result.",
      trigger: "Use before logging provider or model provenance for a result.",
      textSha256: "477c14a635a787f8b6e4545841541571f298b4790c344980b1bf6e2aee2d7f06",
      audioSha256: "ffa93ab270796d7c212098c8a68c09f4ad263e8e64f6246840ea6f9a78462f36",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/model-provider-receipt.json",
    ),
  ],
  "orchestration.plan_routes": [
    RowanActionClip(
      eventId: "orchestration.plan_routes",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.plan_routes",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-plan-routes.wav",
      caption: "I can split the work across independent routes.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use when planning independent cross-provider or multi-route work.",
      trigger: "Use when planning independent cross-provider or multi-route work.",
      textSha256: "3d4b98fedd01954fd533086158035335fd47b1335825df7696554bd32ad7b632",
      audioSha256: "0d1d0f79cd2f530dc0f2dea430b2e71ecca77c1a2757e5b5e8c601b2f7dcf7d2",
      durationSeconds: 3.12,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/orchestration-plan-routes.json",
    ),
  ],
  "orchestration.same_prompt": [
    RowanActionClip(
      eventId: "orchestration.same_prompt",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.same_prompt",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-same-prompt.wav",
      caption: "I'll keep the prompt consistent across the comparison.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use when preparing a same-prompt provider or model comparison.",
      trigger: "Use when preparing a same-prompt provider or model comparison.",
      textSha256: "4016a5213ad26f2e6cd240db511c0c078e041dfd26861905503a7471777e3131",
      audioSha256: "81dd1c1b3c8a0afe7e3395a5adc068ae93a7641dc20f026cb606d077e4649931",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/orchestration-same-prompt.json",
    ),
  ],
  "orchestration.compare_outputs": [
    RowanActionClip(
      eventId: "orchestration.compare_outputs",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.compare_outputs",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-compare-outputs.wav",
      caption: "I'll compare the outputs before I rely on them.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use before evaluating outputs from more than one route.",
      trigger: "Use before evaluating outputs from more than one route.",
      textSha256: "be223d4f2b1785e26b796e241644f06bb77204bf578e8d302bb07464ba2b3bbc",
      audioSha256: "323afb31fd32ce3872ec7d6d88b4d94d4f65e9b70b4a2abdbd7a835c1467e192",
      durationSeconds: 2.72,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/orchestration-compare-outputs.json",
    ),
  ],
  "orchestration.disagreement": [
    RowanActionClip(
      eventId: "orchestration.disagreement",
      clipId: "cartesia-rowan-complete-pack/v1:orchestration.disagreement",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/orchestration-disagreement.wav",
      caption: "The routes disagree. I'll trace the difference.",
      category: "cross_provider_orchestration",
      context: "cross_provider_orchestration",
      prerequisite: "Use only after two or more route outputs conflict.",
      trigger: "Use only after two or more route outputs conflict.",
      textSha256: "8ab4539e8a0d5518d2420470c59be43f3fba63e4130776448723a03662f3eb14",
      audioSha256: "4de91a811239ea2e2bc292371e068474fab6b5af1232d7c3a377ea6907fc3d85",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/orchestration-disagreement.json",
    ),
  ],
};
