import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData12 = <String, List<RowanActionClip>>{
  "reaction.small_next_step": [
    RowanActionClip(
      eventId: "reaction.small_next_step",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.small_next_step",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/small-next-step.wav",
      caption: "Let's keep the next step small.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "6aef34fb6a94e0ffed3bb3bb12c974ba7a8a00b17227ce8c4d7c642f527566f1",
      audioSha256: "d7bb61dccaed98c8316ae1272f691d4243554bb39f82316f749cfebd9f664af1",
      durationSeconds: 1.68,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/small-next-step.json",
    ),
  ],
  "reaction.thanks_patience": [
    RowanActionClip(
      eventId: "reaction.thanks_patience",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.thanks_patience",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/thanks-patience.wav",
      caption: "Thanks for sticking with it.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "9b713d0d34beb5f568bb1714223d4e1208fef17ba2d6061ad7d9a9e7e0d55ed3",
      audioSha256: "a8f2ba2da2f81660c7e0be16728d7034438f29b7a5743cc60112eeccf1736222",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/thanks-patience.json",
    ),
  ],
  "reaction.offer_example": [
    RowanActionClip(
      eventId: "reaction.offer_example",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.offer_example",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/offer-example.wav",
      caption: "Would an example help?",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "b4ced6a527bdd289d7a85e963afcbe3482aca1b55be8a456c4a07799e4af906b",
      audioSha256: "0639103d10f2f9ee78ebe814e040e90485de867e80a763e25c8d67f5299f1d56",
      durationSeconds: 1.6,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/offer-example.json",
    ),
  ],
  "reaction.offer_walkthrough": [
    RowanActionClip(
      eventId: "reaction.offer_walkthrough",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.offer_walkthrough",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/offer-walkthrough.wav",
      caption: "I can walk you through it.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "679b3c98b9386252479d30726f6a14af3593e36b52587bad709583232f63c216",
      audioSha256: "087a529215dfb4bbfec227a966f3209be18eff8ed1dda3ede0f705bdd38d80c5",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/offer-walkthrough.json",
    ),
  ],
  "reaction.compare_versions": [
    RowanActionClip(
      eventId: "reaction.compare_versions",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.compare_versions",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/compare-versions.wav",
      caption: "Let's compare the two versions.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "0560d1e5568ddc72da669d6a726b66d746423df51116709123158cec673f5ea6",
      audioSha256: "c21c3afac545a8b036ff89c9f32c1a9cab995ced4228be90c4b2e9a4bf364be7",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/compare-versions.json",
    ),
  ],
  "reaction.user_in_control": [
    RowanActionClip(
      eventId: "reaction.user_in_control",
      clipId: "cartesia-rowan-complete-pack/v1:reaction.user_in_control",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/user-in-control.wav",
      caption: "You're in control. We can pause here.",
      category: "reactions",
      context: "reactions",
      prerequisite: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      trigger: "Use only when this response fits the current user interaction; never as evidence of task completion.",
      textSha256: "51aea12ff2b9e1e004f04e6d6733c52baeb856cb62a3e884c41ed941defcdc34",
      audioSha256: "ddb20e40f571855d6281e802af8755bfa34fcc59bcbf60cf74c070763c8630ee",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/user-in-control.json",
    ),
  ],
  "operation.ready": [
    RowanActionClip(
      eventId: "operation.ready",
      clipId: "cartesia-rowan-action-pack/v1:operation.ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-ready.wav",
      caption: "Ready when you are.",
      category: "operation",
      context: "operation",
      prerequisite: "Use when the UI is idle and the user has initiated or entered a context where Rowan can act.",
      trigger: "Use when the UI is idle and the user has initiated or entered a context where Rowan can act.",
      textSha256: "182bf2ce919b1a734c04bfa0ad74bf1b4ddd19993cf6311edc870f5dee209184",
      audioSha256: "b3df1ea63b5c5a7c1d3ffcf478fddff3f895d3561cfb9db96ef20e2e19f0df0f",
      durationSeconds: 1.04,
      recommendedCooldownSeconds: 1.5,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "operation.started": [
    RowanActionClip(
      eventId: "operation.started",
      clipId: "cartesia-rowan-action-pack/v1:operation.started",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-working-started.wav",
      caption: "I'm starting the run now.",
      category: "operation",
      context: "operation",
      prerequisite: "Use only after a run request has been accepted for start.",
      trigger: "Use only after a run request has been accepted for start.",
      textSha256: "f6feedff06ef0bc69f28168f709ca5da08b4664ff799b116636f5dde7a0502f3",
      audioSha256: "4876b23578e28292300391031327740d8fcd5a7c68a944d9f3e56d83b60ce917",
      durationSeconds: 1.52,
      recommendedCooldownSeconds: 2,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "operation.working": [
    RowanActionClip(
      eventId: "operation.working",
      clipId: "cartesia-rowan-action-pack/v1:operation.working",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-working.wav",
      caption: "I'm working on it now.",
      category: "operation",
      context: "operation",
      prerequisite: "Use for bounded progress once work has actually begun.",
      trigger: "Use for bounded progress once work has actually begun.",
      textSha256: "c66814d23ec882529a601eceae09a5ab1efdd9eb9ccfbcc18181714c410853e1",
      audioSha256: "d8af2b4dab047691c3a89fe0bf61b5c19304d4f26ad88caa559237e895ba422d",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 8,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "input.required": [
    RowanActionClip(
      eventId: "input.required",
      clipId: "cartesia-rowan-action-pack/v1:input.required",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-needs-input.wav",
      caption: "I need your input before I continue.",
      category: "input",
      context: "input",
      prerequisite: "Use only when execution is blocked on user input.",
      trigger: "Use only when execution is blocked on user input.",
      textSha256: "c4dedd8cf9462a790a178a98be61122b60c628a63a56380521ef80e4893a54a0",
      audioSha256: "bb8d237c70bc12f945de7c2afaf68670e35f6657b31f6a85bb1ae2d658c54725",
      durationSeconds: 2.08,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "approval.waiting": [
    RowanActionClip(
      eventId: "approval.waiting",
      clipId: "cartesia-rowan-action-pack/v1:approval.waiting",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-approval-waiting.wav",
      caption: "This needs your approval before it can proceed.",
      category: "approval",
      context: "approval",
      prerequisite: "Use only when an approval/grant is waiting.",
      trigger: "Use only when an approval/grant is waiting.",
      textSha256: "ab7da536c634a7b7261888e3bf31803dc4f73a6c0d7b0d6813ecee0cd8c4a4ba",
      audioSha256: "fa3079260d617458d896f0e93450bf878d8e736c925365d762fc0dd2ed1f3b16",
      durationSeconds: 2.64,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
  "operation.paused": [
    RowanActionClip(
      eventId: "operation.paused",
      clipId: "cartesia-rowan-action-pack/v1:operation.paused",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/cartesia-rowan-action-pack-paused.wav",
      caption: "I've paused the run.",
      category: "operation",
      context: "operation",
      prerequisite: "Use only after the run is actually paused.",
      trigger: "Use only after the run is actually paused.",
      textSha256: "ac333c10415e0c2609413aa0fdbb24afd97c71f7a7d5b1613caaa2c144871bb3",
      audioSha256: "dc8bd82f30d7fb4d81e170e6d731c63a731d9d41b5e41a81669e246439205143",
      durationSeconds: 1.28,
      recommendedCooldownSeconds: 3,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-action-pack",
      generation: "reused",
      provenanceBasis: "source_manifest_reuse",
    ),
  ],
};
