import 'rowan_action_cue_clip_model.dart';
import 'rowan_action_cue_pack_provenance.dart';

const rowanCartesiaActionCueClipData6 = <String, List<RowanActionClip>>{
  "studio.voice_preview": [
    RowanActionClip(
      eventId: "studio.voice_preview",
      clipId: "cartesia-rowan-complete-pack/v1:studio.voice_preview",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-voice-preview.wav",
      caption: "I can preview the voice before generating the set.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use when offering a voice audition before batch generation.",
      trigger: "Use when offering a voice audition before batch generation.",
      textSha256: "715314478c1c0decd91bb6e7e1a11bebef838278af085d9fda3cef154e47c0d9",
      audioSha256: "439caaa63788fbdb3738cfc50b32062e57013aaa31381deb9909c8bc55b137f5",
      durationSeconds: 2.96,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-voice-preview.json",
    ),
  ],
  "studio.mix_level": [
    RowanActionClip(
      eventId: "studio.mix_level",
      clipId: "cartesia-rowan-complete-pack/v1:studio.mix_level",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-mix-level.wav",
      caption: "I'll keep the mix level conservative.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use when setting safe audio mix levels.",
      trigger: "Use when setting safe audio mix levels.",
      textSha256: "b501fb463b8d805cca2e1b33752ddf15df2beb6eba0e185414e06b50c622e11d",
      audioSha256: "4f908b9cd1facda5d5a851392451a34173b48074785722a50dd730ebd735a48f",
      durationSeconds: 2.08,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-mix-level.json",
    ),
  ],
  "studio.asset_missing": [
    RowanActionClip(
      eventId: "studio.asset_missing",
      clipId: "cartesia-rowan-complete-pack/v1:studio.asset_missing",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-asset-missing.wav",
      caption: "An asset is missing. I'll locate the source.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use only after an expected asset is unavailable.",
      trigger: "Use only after an expected asset is unavailable.",
      textSha256: "06935eac67612353302a8dfc30d3e65910945384977fbefe4afea39c39176573",
      audioSha256: "ada9ade0d54a61e458d884cc148ea6378f9ffd3c6b18b8d19ba68a2315ac6681",
      durationSeconds: 2.56,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-asset-missing.json",
    ),
  ],
  "studio.frame_compare": [
    RowanActionClip(
      eventId: "studio.frame_compare",
      clipId: "cartesia-rowan-complete-pack/v1:studio.frame_compare",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-frame-compare.wav",
      caption: "I can compare these frames side by side.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use when offering visual comparison.",
      trigger: "Use when offering visual comparison.",
      textSha256: "4f31dd5f7c4af8c31aec1cfc485fea4a27f64969fcc0a928e75a8d92a51d3796",
      audioSha256: "ac5224a61217f41d5e75a3e8849c8bba4afaeff040656739865fc37a39abccf5",
      durationSeconds: 2.88,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "low",
      receiptFile: "receipts/studio-frame-compare.json",
    ),
  ],
  "studio.render_queued": [
    RowanActionClip(
      eventId: "studio.render_queued",
      clipId: "cartesia-rowan-complete-pack/v1:studio.render_queued",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-render-queued.wav",
      caption: "The render is queued.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use only after the render job is queued.",
      trigger: "Use only after the render job is queued.",
      textSha256: "0a026988cebf44be95b6791de3238981a4df06c83511592e93a60b5a90a1854c",
      audioSha256: "153ef17c7bcc0bf94148910c11d10133e79c6b0b2dff6da29ba63f49014dc282",
      durationSeconds: 1.68,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "saved_history_and_ui",
      priority: "medium",
      receiptFile: "receipts/studio-render-queued.json",
    ),
  ],
  "studio.render_review": [
    RowanActionClip(
      eventId: "studio.render_review",
      clipId: "cartesia-rowan-complete-pack/v1:studio.render_review",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/studio-render-review.wav",
      caption: "The render is ready for review.",
      category: "studio_visual_audio",
      context: "studio_visual_audio",
      prerequisite: "Use only after render output exists.",
      trigger: "Use only after render output exists.",
      textSha256: "ec27a976cfc537fc814ca1c7a345c44fcd8c17abb5e3b3f4c9bbc58d8d504e4a",
      audioSha256: "a961abbb0ea45a7f460adfb74b2b26f26443b67547b01254820e6cd18ceb81d7",
      durationSeconds: 2.4,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/studio-render-review.json",
    ),
  ],
  "code.inspect_repo": [
    RowanActionClip(
      eventId: "code.inspect_repo",
      clipId: "cartesia-rowan-complete-pack/v1:code.inspect_repo",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-inspect-repo.wav",
      caption: "I'll inspect the repo before editing.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before repository edits or behavior claims.",
      trigger: "Use before repository edits or behavior claims.",
      textSha256: "6d62639a4d07013e0c3998feb68d77b463e037425b9a3cb2a2c3208c34f4a48b",
      audioSha256: "72653aed187f61bb5e8149de7e2cd4b7e9e104be055b9eef493678cb3c9d100a",
      durationSeconds: 2.32,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/code-inspect-repo.json",
    ),
  ],
  "code.open_file": [
    RowanActionClip(
      eventId: "code.open_file",
      clipId: "cartesia-rowan-complete-pack/v1:code.open_file",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-open-file.wav",
      caption: "I'll open the file that owns this behavior.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before reading the responsible file.",
      trigger: "Use before reading the responsible file.",
      textSha256: "b066d322d265737deb5301b7aee9535e1dbfaece6984b04b48edcfde91afe9e7",
      audioSha256: "7347f0455d19a0ce6e5e73eb8a70b50303c2cb3c8defb0d81cbe266150ffa6ed",
      durationSeconds: 2.48,
      recommendedCooldownSeconds: 20,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/code-open-file.json",
    ),
  ],
  "code.patch_ready": [
    RowanActionClip(
      eventId: "code.patch_ready",
      clipId: "cartesia-rowan-complete-pack/v1:code.patch_ready",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-patch-ready.wav",
      caption: "I have a patch ready to review.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use only after a patch exists.",
      trigger: "Use only after a patch exists.",
      textSha256: "2a08c564c9a99b7d1f8e549eff0631b573f44356fb0c329c131a175cfa6f3aa0",
      audioSha256: "d506b846b68cd9e3a482c82560c3a5426d0ff05eeba0258397f8d90d985deb95",
      durationSeconds: 2,
      recommendedCooldownSeconds: 45,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/code-patch-ready.json",
    ),
  ],
  "code.test_target": [
    RowanActionClip(
      eventId: "code.test_target",
      clipId: "cartesia-rowan-complete-pack/v1:code.test_target",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-test-target.wav",
      caption: "I'll run the focused check for this change.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before running a focused test or validation command.",
      trigger: "Use before running a focused test or validation command.",
      textSha256: "d3d96a51181c56442910b8356a0463b260bb0fec10b8f63fada7296d15d3bf4f",
      audioSha256: "cef84c750a436c46ba2890bb245e4755a1423be4d6f1d36e5ac60b0589d03e4c",
      durationSeconds: 2.24,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "high",
      receiptFile: "receipts/code-test-target.json",
    ),
  ],
  "code.lint_target": [
    RowanActionClip(
      eventId: "code.lint_target",
      clipId: "cartesia-rowan-complete-pack/v1:code.lint_target",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-lint-target.wav",
      caption: "I'll run the relevant lint check.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before running lint for a change.",
      trigger: "Use before running lint for a change.",
      textSha256: "db73f38eb5992b1debbacaf8e4a175455a5e188e2bae22465ac65fb6869d19e5",
      audioSha256: "0e5d65e24a88b903a77989eca3e767a36b4064add560526e37542cb9cf471058",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "saved_history_and_ui",
      priority: "medium",
      receiptFile: "receipts/code-lint-target.json",
    ),
  ],
  "code.build_target": [
    RowanActionClip(
      eventId: "code.build_target",
      clipId: "cartesia-rowan-complete-pack/v1:code.build_target",
      variantId: "v1",
      assetKey: "rowan/action-cues/cartesia-rowan-complete-pack/audio/code-build-target.wav",
      caption: "I'll run the relevant build check.",
      category: "coding_tools",
      context: "coding_tools",
      prerequisite: "Use before running a build command.",
      trigger: "Use before running a build command.",
      textSha256: "006abacb2d7de6585a7cfd1d940b1a7515d6c6c56bbd13e5e463ce8af25e774f",
      audioSha256: "a8c83bcee08d678aee2317bd7b6f5e4d2c3f11d00d91a5e48c16370e068f0113",
      durationSeconds: 1.76,
      recommendedCooldownSeconds: 30,
      manifestSha256: rowanCartesiaCompletePackManifestSha256,
      sourcePack: "cartesia-rowan-complete-pack",
      generation: "new",
      provenanceBasis: "captured_generation_request",
      priority: "medium",
      receiptFile: "receipts/code-build-target.json",
    ),
  ],
};
